; start.asm -- 3com-pktdrv cold entry + JIT composer (fully assembly, no C runtime).
;
; The driver is a single self-specializing TSR (docs/02). At load, COLD code detects the
; machine, then COMPOSES the hot path from position-independent fragments (build/frags_asm.inc,
; generated by tools/mkfrag.py from src/asm/frag/*.asm), baking decisions in as immediates.
; copy-down then packs the emitted image and DOS-keeps it; everything here is reclaimed.
;
; This file is the cold orchestration + composer. It must itself be 8088-clean (it runs on
; a 5150). The emitted hot path is the fragments, not this code.
;
; Build: nasm -f obj -> wlink (system dos). Entry point is ..start. No C, no C library.

cpu 8086
bits 16

%include "codegen.inc"
; Shared EL3 register constants (guarded; also pulled by the probe). build_plan needs them
; to compute the per-generation Window-1 base + TX-start command.
%include "el3_core.inc"
; Corkscrew (3C515) delta: bus-master DMA register block + descriptor layout (guarded; also
; pulled by isapnp). The resident TX DMA paths + the descriptor/ring reservations need these.
%include "el3_corkscrew.inc"
; Proprietary RX checksum-offload vendor extension (AH=0xF2) constants.
%include "rx_cksum.inc"

;==============================================================================
; DATA (initialized) -- fragment palette, plan template
;==============================================================================
segment _DATA public class=DATA use16

%include "frags_asm.inc"        ; f_*[], *_patches[], g_frags[], FRAG_TABLE_N

; The emit plan for a 3C509B (PIO floor): only the DATAPATH fragments are emitted -- the
; API dispatch and ISR are static resident code (resident.asm/isr.asm), which call the
; emitted TX/RX via g_off[]. Each step: db id ; dw imm0 (io_base, filled by build_plan).
g_plan:
    db FRAG_RX_PIO
g_plan_rx_imm:
    dw 0
    db FRAG_TX_PIO
g_plan_tx_imm:
    dw 0
G_PLAN_N        equ 2
PLAN_STEP_SIZE  equ 3

; diagnostic strings ($-terminated for INT 21h AH=09h)
msg_banner  db '3com-pktdrv floor (3C509 packet driver)', 13, 10, '$'
msg_cpu     db 'CPU class=', '$'
msg_nic     db 13, 10, '3C509 I/O=0x', '$'
msg_irq     db ' IRQ=0x', '$'
msg_mac     db ' MAC=', '$'
msg_no_nic  db 13, 10, 'No 3C509 found', 13, 10, '$'
msg_badmac  db 'ERROR: invalid station MAC (all-FF/all-00/multicast) -- wrong card gen?', 13, 10
            db '       (/5 selects 3C515 EEPROM at +0x2000; omit it for a 3C509)', 13, 10, '$'
msg_crlf    db 13, 10, '$'
msg_dma     db 'DMA=', '$'
msg_dma_on  db 'ON', 13, 10, '$'
msg_dma_pio db 'PIO', 13, 10, '$'
msg_cb      db 'COPYBREAK T=0x', '$'
msg_coh        db 'CACHE FLUSH=', '$'           ; Phase 2 RX coherency verdict report
msg_coh_none   db 'NONE (coherent)', 13, 10, '$'
msg_coh_wbinvd db 'WBINVD (non-coherent)', 13, 10, '$'
msg_coh_evict  db 'SW-EVICT (non-coherent, 386)', 13, 10, '$'
msg_nc_eff     db 'NC=validated (pool fenced; flush kept, docs/17 4b)', 13, 10, '$'
msg_nc_off     db 'NC=requested, not effective (flush kept)', 13, 10, '$'

; uninstall (`3cpd /u`)
sig_pktdrvr db 'PKT DRVR'                       ; resident signature (handler + 3); 8 bytes
msg_uninst  db 13, 10, '3com-pktdrv uninstalled', 13, 10, '$'
msg_notinst db 13, 10, '3com-pktdrv not installed', 13, 10, '$'

%ifdef CFG_FAKENIC
fake_mac    db 0x02, 0x60, 0x8C, 0x11, 0x22, 0x33   ; test MAC (3Com OUI 00:60:8C)
%endif

%ifdef CFG_DEBUG
msg_dbgon   db '[debug build]', 13, 10, '$'
msg_eeprod  db 13, 10, 'EEPROM prod=0x', '$'
msg_eeid    db ' mfg=0x', '$'
msg_emit    db 'emitted=0x', '$'
msg_keep    db ' resident para=0x', '$'
msg_inst    db 13, 10, 'INSTALLED: INT 60h, IRQ vec=0x', '$'
%endif

;==============================================================================
; BSS -- COLD scratch only (above resident_end, reclaimed after install).
;==============================================================================
segment _BSS public class=BSS use16

g_cpu_class:    resb 1          ; CPU_8088 .. CPU_CPUID (set by detect_cpu)
g_nic_gen:      resb 1          ; detected generation: 0 = Tomahawk (3C509/B), 1 = Corkscrew (3C515)
g_manual:       resb 1          ; 1 = manual /b= I/O base given -> skip the ID-port probe
g_force8:       resb 1          ; 1 = /8 given -> force the 8088-class (8-bit byte-loop) datapath
g_force286:     resb 1          ; 1 = /2 given -> force the 286-class datapath (16-bit PIO + single-transfer DMA)
g_want_dma:     resb 1          ; 1 = /d given -> request bus-master TX DMA (resolved in build_plan)
g_want_large:   resb 1          ; 1 = /j given -> request FDDI-sized large frames (gated to 3C515)
tail_end:       resw 1          ; PSP command-tail end offset (cold arg scan)
g_emitted_len:  resw 1
g_keep_para:    resw 1

; composer scratch
g_pos:          resw 1          ; current write offset into resident_image
g_planptr:      resw 1
g_step:         resw 1
g_imm0:         resw 1
g_curid:        resb 1
                resb 1

%ifdef CFG_PNP
; ISA PnP isolation scratch (cold)
pnp_lfsr:       resb 1          ; running isolation checksum LFSR
pnp_saw:        resb 1          ; a card drove the bus (0x55AA seen)
pnp_next_csn:   resb 1          ; next CSN to hand out
pnp_found_csn:  resb 1          ; CSN of the matched 3Com card
pnp_id:         resb 9          ; isolated serial id: vendor[2] product[2] serial[4] csum[1]
                resb 1          ; pad to even
%endif

;==============================================================================
; STACK -- COLD: the composer/init working stack (reclaimed; the ISR uses isr_stack).
;==============================================================================
segment _STACK stack class=STACK use16
        resb 1024

;==============================================================================
; CODE
;
; _TEXT is in DGROUP (tiny model): CS = DS = ES = SS = DGROUP, one addressable segment, so
; the resident INT 60h handler / ISR (next milestone) can NEAR-call the emitted datapath in
; resident_image. The _BSS + _STACK tail is uninitialized -> minalloc, not stored in the file.
;==============================================================================
group DGROUP _TEXT _DATA _BSS _STACK
segment _TEXT public class=CODE use16

;==============================================================================
; RESIDENT region (kept) -- laid out FIRST so the TSR keeps only up to resident_end and
; reclaims everything after it (the cold composer / probe / init / diagnostics). Holds the
; INT 60h handler, the ISR, the resident state they touch, and the JIT-emitted datapath.
; resb here is stored in the file but stays resident (it must be low/kept).
;==============================================================================
%include "resident.asm"             ; pkt_handler (INT 60h API)
%include "isr.asm"                  ; nic_isr (RX + receiver upcall)
%include "cache.asm"                ; bus-master DMA cache-coherency flush helper (Phase 2)
%include "nc.asm"                   ; non-cacheable DMA-region marking (Phase 2 step 4; opt-in /n, real-HW only)

g_nic_io:       resw 1              ; detected I/O base (command reg at +0x0E, windowed cfg at +0x00..)
g_nic_irq:      resw 1              ; detected IRQ
g_w1_base:      resw 1              ; Window-1 data-register base = io_base + gen delta (FIFO/status/free)
g_tx_start:     resw 1              ; precomputed SET_TX_START command (early-start vs store-and-forward)
g_use_dma:      resb 1             ; 1 = bus-master DMA TX active (3C515, >=286): single-transfer on 286, ring on 386+
g_use_large:    resb 1             ; 1 = FDDI-sized large frames active (/j AND 3C515): allowLargePackets
g_rx_len_mask:  resw 1             ; RX length mask: 0x07FF std, 0x1FFF when large (13-bit 3C515 field)
g_copybreak_t:  resw 1             ; RX copybreak threshold (bytes): len<=T -> PIO, len>T -> DMA ring.
                                   ; autotuned at install (copybreak_autotune): T = c_setup / a_PIO.
g_tx_done:      resb 1             ; set by the ISR on TxComplete; awaited by dma_tx_single (286 path)
g_tx_ring:      resb 1             ; 1 = 386+ -> non-blocking COPY ring (movsd) for send_pkt; 0 = 286 -> blocking single-transfer
g_async:        resb 1             ; 1 = zero-copy async TX ring available (AH=0xF1): any bus-master config (>=286)
g_rx_cksum:     resb 1             ; 1 = RX checksum offload on -> sum IP+TCP+payload during the PIO drain (AH=0xF2)
g_rx_cksum_val: resw 1             ; folded native-LE ones-complement sum of the last drained frame
g_cache_flush_fn: resw 1           ; Phase 2: offset of the selected DMA cache-flush helper (cache.asm). The
                                   ; DMA paths `call word [g_cache_flush_fn]`; the cold coherency self-test
                                   ; (docs/17) picks the tier. Default cache_flush_none (coherent) until then.
g_flush_tier:   resb 1             ; Phase 2: FLUSH_TIER_* verdict from phase_validate_coherency (cold). install
                                   ; maps it -> g_cache_flush_fn. Set NONE at the top of the cold probe so the
                                   ; PIO path (probe skipped) still has a defined value.
g_nc_chipset:   resb 1             ; Phase 2 step 4: /n=<id> opt-in NC chipset (0 = off; NC_CHIP_*). Set by the
                                   ; cold arg scan, read at f_xms_configure (resident) -> must NOT be in cold BSS.
g_nc_effective: resb 1             ; 1 = the cold NC re-test confirmed NC fences the cache -> f_xms_configure marks
                                   ; the ring NC and drops the flush. 0 (default/emulator) -> keep the flush tier.
g_lin_delta:    resd 1             ; Phase 2 4b: CONV/COMMONBUF in-place delivery linear-vs-physical offset =
                                   ; cfg.lin0 - cfg.phys0 (set in f_xms_configure .build_conv). 0 for CONV (real
                                   ; mode, identity-mapped). Under a paging VMM (COMMONBUF/VDS) phys0 is the bus
                                   ; address and lin0 the V86 linear the CPU uses; the ISR recovers each slot's
                                   ; CPU segment as (descriptor.phys + g_lin_delta) >> 4. RESIDENT (ISR reads it).
; (the bus-master TX-DMA structures -- tx_descs / tx_slots -- are placed LAST, past resident_end_pio,
;  so the TSR drops them on the PIO floor; the 286 single-transfer path also drops tx_slots.)
g_mac:          resb 6             ; station address
; receiver handle table: per slot recv_off, recv_seg (0=free), type (0=match all)
htable:         resb MAX_HANDLES * HANDLE_SIZE

; ISR type-demux scratch
rx_len:         resw 1             ; current packet length
cur_handle:     resw 1             ; matched handle (slot offset)
appbuf_off:     resw 1             ; receiver's buffer (upcall-1 result)
appbuf_seg:     resw 1
hdr_buf:        resb 16            ; Ethernet header peek (14 bytes + pad)

; install/uninstall state (resident so the uninstall vendor fn can restore + free)
psp_seg:        resw 1             ; our PSP segment
old_int_off:    resw 1             ; previous INT 60h owner (off,seg for `lds`)
old_int_seg:    resw 1
old_irq_off:    resw 1             ; previous NIC IRQ owner
old_irq_seg:    resw 1
irq_vec:        resb 1             ; computed NIC IRQ vector number
                resb 1

g_off:          resw FRAG__COUNT   ; emitted-fragment offsets (handler/ISR call via these)
g_isr_busy:     resb 1             ; ISR reentrancy guard
isr_work:       resb 1             ; per-interrupt RX work cap counter (MAX_RX_WORK down to 0)
isr_save_ss:    resw 1             ; interrupted task's SS:SP (private-stack switch)
isr_save_sp:    resw 1
isr_stack:      resb 128           ; the ISR's private stack
isr_stack_top:
resident_image: resb 256           ; the composed datapath (tx + rx drain)

; --- statistics (resident; updated by the ISR / send_pkt, read by get_statistics) ---
stat_rx:        dw 0               ; packets received & delivered
stat_tx:        dw 0               ; packets transmitted
stat_rxerr:     dw 0               ; RX errors (card-flagged)
stat_rxdrop:    dw 0               ; RX dropped (no receiver / no buffer)
stat_irq:       dw 0               ; NIC interrupts serviced
stat_txunderrun: dw 0              ; TX underrun/jabber recoveries (early-start tuning)
stat_txwait:    dw 0               ; TX FIFO-room waits that timed out (fast-CPU stall)
stat_adapterfail: dw 0            ; adapter-failure RX-engine resets (ISR self-heal)
pkt_stats:      times 7 dd 0       ; Crynwr get_statistics struct (built on demand)

%ifdef CFG_DEBUG
; --- debug event-log ring (resident; appended by the ISR / handler, dumped by pktdbg) ---
DBG_LOG_SIZE    equ 512
dbg_sig:        db 'PKTDBG00'      ; marker the dump tool can recognise
dbg_log_head:   dw 0               ; ring write index (wraps at DBG_LOG_SIZE)
dbg_log:        times DBG_LOG_SIZE db 0
%endif

; --- end of the always-resident (PIO floor) region. When the bus-master DMA path is inactive
;     (g_use_dma == 0) the TSR keeps only up to here, reclaiming the DMA region below (~4.6 KB).
resident_end_pio:
global resident_end_pio

; bus-master TX-DMA structures -- kept ONLY when the DMA path is active (gated on g_use_dma), so
; they sit past resident_end_pio and the PIO floor drops them. RX is always PIO (no RX-DMA buffer/
; descriptor), so only the TX descriptors + ring slots live here. Descriptor layout matches the
; emulator EL3 Down desc (next/status/addr/length). tx_descs[0] doubles as the 286 single-transfer
; down descriptor (the ring is 386+ only); the TX slots below the single boundary exist only for the
; 386+ ring, so the 286 path drops them too.
; Phase 2 (docs/17 Piece 3/4): cache-line (32-byte) align the card-DMA-touched descriptor block so it
; never shares a line with the CPU-hot ring counters below it (TX_RING_N*16 = 64 B = a clean 2 lines,
; so the counters start on a fresh line) -- a future line-granular flush then can't corrupt either.
                alignb 32
tx_descs:       resb TX_RING_N * EL3_DESC_SIZE  ; TX ring descriptors (card DMA-reads them); [0] also serves the 286 single-transfer
                alignb 4
; TX ring counters -- resident on ALL bus-master configs (incl. 286): the zero-copy async ring
; (dma_tx_async) is 8086-clean and needs no per-frame slot copy, so it works on a 286 too. Only the
; ~10 bytes of counters live here; the 6 KB tx_slots stay 386+-only (they back the COPY ring, which a
; 286 can't hide). The ISR also reads tx_ring_count to tell a ring completion from a single-transfer.
tx_ring_head:   resw 1             ; next slot to fill (producer: send_pkt / async_send)
tx_ring_tail:   resw 1             ; oldest in-flight slot (consumer: TxComplete ISR)
tx_ring_count:  resw 1             ; frames currently queued (0..TX_RING_N); 0 => any TxComplete is a single-transfer
tx_dma_busy:    resb 1             ; 1 while a slot's DMA is in flight
                resb 1             ; pad to even
tx_completed:   resw 1             ; ASYNC ext: frames the TxComplete ISR has finished (wraps mod 65536);
                                   ; ASYNC_INFO hands the stack &tx_completed to throttle posts on.

resident_end_single:               ; <== TSR keep boundary for the 286 single-transfer DMA path (descriptors + ring counters)
global resident_end_single

; XMS DMA receive ring state -- present whenever g_use_dma=1 (286 or 386+).
; 286: kept through resident_end_xms_single (drops tx_slots / ring vars).
; 386+: kept through resident_end (includes tx_slots for the TX ring).
xms_dma_armed:  resb 1             ; 0 = PIO / not configured; 1 = XMS ring armed
xms_rx_policy:  resb 1             ; xms_mem_policy_t (VCPI=0, DPMI=1, XMS_COPY=2)
xms_slot_idx:   resb 1             ; current ring slot index (0..xms_nslots-1; cycles mod nslots)
xms_nslots:     resb 1             ; ring depth: 2 (XMS_COPY/286 ping-pong) or RX_RING_N (CONV+386 deep ring)
xms_cfg_off:    resw 1             ; far ptr to caller's xms_rx_cfg_t (offset)
xms_cfg_seg:    resw 1             ; far ptr to caller's xms_rx_cfg_t (segment)
xms_slot_sz:    resw 1             ; bytes per XMS slot
g_rx_irq_masked: resb 1            ; NAPI: 1 = UP_COMPLETE IRQ masked under RX load; the conv-ring drain
                                   ; is deferred to pkt_xms_poll (task) so the ISR can't starve net_poll
                resb 1             ; pad to word alignment
g_intr_enb_full: resw 1           ; full SetIntrEnb mask (incl UP_COMPLETE) saved at configure; the ISR
                                   ; masks UP_COMPLETE out of it, pkt_xms_poll re-arms with the full value
                alignb 32
; RX up-descriptor ring: RX_RING_N entries, cache-line (32-byte) aligned (Phase 2, docs/17 Piece 3:
; the card writes UP_COMPLETE here and the CPU polls it -- a non-coherent cache must invalidate this
; line before the poll, so it must not share a line with neighbouring CPU-written state; RX_RING_N*16 =
; 128 B = a clean 4 lines). CONV uses all N (deeper ring, contiguous slots); XMS_COPY / 286 single-
; transfer use the first 2. desc[i] = xms_rx_descs + i*EL3_DESC_SIZE.
xms_rx_descs:   resb RX_RING_N * EL3_DESC_SIZE
xms_rx_desc0    equ xms_rx_descs                    ; slot-0 alias (the XMS_COPY / 286 2-slot path)
xms_rx_desc1    equ xms_rx_descs + EL3_DESC_SIZE    ; slot-1 alias
xms_gdt:        resb 48            ; INT 15h AH=87h GDT (6 x 8-byte entries; access bytes pre-set)

resident_end_xms_single:          ; <== TSR keep boundary: 286 DMA + XMS (drops TX ring slots)
global resident_end_xms_single

                alignb 32                       ; Phase 2 (docs/17 Piece 4): cache-line align the DMA TX slots
                                                ; (card reads them; TX_SLOT_SZ=1536 is a multiple of 32, so
                                                ; every slot stays line-aligned) -- 386+-only, past the 286 boundary
tx_slots:       resb TX_RING_N * TX_SLOT_SZ     ; 386+ COPY-ring frame slots (dma_tx_enqueue movsd's the frame in)

resident_end:                      ; <== TSR keep boundary for the 386+ ring DMA path
global resident_end

;==============================================================================
; COLD region (reclaimed after install) -- entry, detection, compose, install, diagnostics.
;==============================================================================
..start:
        mov     bp, es              ; ES = PSP at .EXE entry -- save for the TSR keep
        mov     ax, DGROUP
        mov     ds, ax
        mov     es, ax              ; composer uses ES:DI for the emit destination
        ; Clear the cold parse/detect flags. They live in _BSS, which DOS does NOT zero on
        ; .EXE load: a fresh boot happens to hand us zeroed memory, but a RELOAD (3cpd /u
        ; then 3cpd again) lands in dirty freed memory -- a stale g_force8 there forces the
        ; 8088 8-bit datapath (wrong on a 16-bit 3C515) and disables DMA. (ES = DGROUP here.)
        cld
        mov     di, g_cpu_class
        mov     cx, 6               ; g_cpu_class, g_nic_gen, g_manual, g_force8, g_force286, g_want_dma
        xor     al, al
        rep     stosb
        ; The NC opt-in state is RESIDENT (read at configure) but set during this cold arg scan, so it can't
        ; ride the cold-BSS clear above. Zero it here so /n unset => off, and a reload starts clean.
        mov     byte [g_nc_chipset], 0
        mov     byte [g_nc_effective], 0
        mov     [psp_seg], bp

        ; --- command tail scan ---
        ;   /u        uninstall the resident driver and exit
        ;   /b=NNN    manual I/O base (hex) -> skip the ID-port probe, attach at NNN
        ;   /q=NN     manual IRQ (decimal)  -> used with /b=
        ; Manual config lets the driver bind to a card at a known base (PnP-only cards, odd
        ; setups, or an emulator) without the ID-port contention.
        mov     es, bp              ; ES = PSP for the tail scan
        mov     al, [es:0x80]       ; command-tail length
        xor     ah, ah
        add     ax, 0x81            ; AX = end offset
        mov     [tail_end], ax
        mov     si, 0x81
.scan_tail:
        cmp     si, [tail_end]
        jae     .args_done
        cmp     byte [es:si], '/'
        jne     .st_next
        mov     al, [es:si + 1]
        or      al, 0x20            ; tolower
        cmp     al, 'u'
        je      do_uninstall
        cmp     al, 'b'
        je      .opt_base
        cmp     al, 'q'
        je      .opt_irq
        cmp     al, '8'
        jne     .chk_286
        mov     byte [g_force8], 1  ; force 8-bit byte-loop datapath (test the 8088 fragment)
        jmp     .st_next
.chk_286:
        cmp     al, '2'
        jne     .chk_dma
        mov     byte [g_force286], 1 ; force 286-class datapath (test 286 16-bit PIO + single-transfer DMA)
        jmp     .st_next
.chk_dma:
        cmp     al, 'd'
        jne     .chk_large
        mov     byte [g_want_dma], 1 ; /d -> request bus-master TX DMA (gated to 3C515 + >=286)
        jmp     .st_next
.chk_large:
        cmp     al, 'j'
        jne     .chk_nc
        mov     byte [g_want_large], 1 ; /j -> request FDDI-sized large frames (gated to 3C515)
        jmp     .st_next
.chk_nc:
        cmp     al, 'n'
        je      .opt_nc             ; /n=<id> -> opt in to a non-cacheable DMA region on a known chipset
.chk_gen:
        cmp     al, '5'
        jne     .st_next
        mov     byte [g_nic_gen], 1 ; /5 -> Corkscrew (3C515): EEPROM +0x2000, W1 base +0x10
.st_next:
        inc     si
        jmp     .scan_tail
.opt_base:
        add     si, 3               ; skip "/b="
        call    parse_hex16         ; ES:SI -> hex -> BX, SI advanced
        mov     [g_nic_io], bx
        mov     byte [g_manual], 1
        jmp     .scan_tail
.opt_irq:
        add     si, 3               ; skip "/q="
        call    parse_dec16         ; ES:SI -> decimal -> BX, SI advanced
        mov     [g_nic_irq], bx
        jmp     .scan_tail
.opt_nc:
        ; /n=<id> -- opt in to a non-cacheable DMA region on a KNOWN chipset (default off). Explicit id (not
        ; a probe) so an unrecognized board never gets speculative 0x22 writes: 1=OPTi 2=Eteq 3=UMC 4=SiS
        ; 254=synthetic structural test. Still re-test-gated before any flush is dropped (nc.asm safety model).
        add     si, 3               ; skip "/n="
        call    parse_dec16         ; ES:SI -> decimal -> BX
        mov     [g_nc_chipset], bl
        jmp     .scan_tail
.args_done:
        mov     ax, DGROUP
        mov     es, ax              ; restore ES = DGROUP for the composer

        mov     dx, msg_banner
        call    print_str
%ifdef CFG_DEBUG
        mov     dx, msg_dbgon
        call    print_str
%endif

        call    detect_cpu          ; -> g_cpu_class
        cmp     byte [g_force8], 0  ; /8 -> force the 8088-class datapath (test 8-bit PIO on a fast CPU)
        je      .chk_force286
        mov     byte [g_cpu_class], CPU_8088
        jmp     .cpu_ok
.chk_force286:
        cmp     byte [g_force286], 0 ; /2 -> force the 286-class datapath (16-bit PIO + single-transfer DMA)
        je      .cpu_ok
        mov     byte [g_cpu_class], CPU_80286
.cpu_ok:
        mov     dx, msg_cpu
        call    print_str
        mov     al, [g_cpu_class]
        add     al, '0'
        call    print_char          ; CPU class digit (0=8088,1=286,2=386)

        ; --- 5150 short-circuit -------------------------------------------------
        ; On an 8088/8086 the capability axis collapses to PIO: no protected mode, no
        ; bus-master, no VMM. The >=286-only cold work (bus-master DMA validation and its
        ; VDS/cache machinery) is deferred to the Corkscrew generation, so today both paths
        ; fall straight through to the floor PIO compose. The split is kept as the documented
        ; hook for that >=286 work.
        cmp     byte [g_cpu_class], CPU_8088
        jbe     .floor
        ; (>=286) bus-master DMA validation moved below -- it needs the activated card + build_plan
.floor:
        ; ISA NIC detection. The native 3Com ID-port sequence is the universal EtherLink III
        ; ISA mechanism and runs on ANY CPU -- it's just port I/O. ISA PnP is a SEPARATE
        ; software protocol over fixed ports (0x279/0xA79 + relocatable read) that ALSO works
        ; on any ISA bus: it is NOT CPU-dependent (no PnP BIOS or 286+ needed to run the
        ; isolation -- a software PnP manager does it). PnP only matters for a 3C509B left in
        ; PnP-only mode or already claimed by a PnP BIOS, so it is a FULL-PROFILE add
        ; (CFG_PNP), compiled out of the minimal floor for size -- gated by profile, not CPU.
%ifdef CFG_FAKENIC
        ; test build (no emulator has a 3C509): skip the probe, inject a fake NIC so the
        ; full el3_init -> compose -> install path runs and the resident driver is testable.
        mov     word [g_nic_io], 0x300
        mov     word [g_nic_irq], 0x000A
        mov     si, fake_mac
        mov     di, g_mac
        mov     cx, 6
        rep     movsb
        clc
%else
        ; manual config (/b= given): skip the ID-port probe, attach at the specified base.
        cmp     byte [g_manual], 1
        jne     .auto_detect
        cmp     word [g_nic_irq], 0
        jne     .have_irq
        mov     word [g_nic_irq], 0x000A    ; default IRQ 10 if /q= omitted
.have_irq:
        call    el3_load_mac_io             ; read MAC via Window-0 EEPROM at the given base
        clc
        jmp     .nic_found
.auto_detect:
%ifdef CFG_PNP
        ; >=286 (16-bit ISA): try ISA PnP first -- it finds a 3C515 AND a PnP-mode 3C509B --
        ; then fall back to the legacy ID-port. On an 8088 a 3C515 can't exist (16-bit card)
        ; so we go straight to the legacy probe and skip the PnP subsystem entirely.
        cmp     byte [g_cpu_class], CPU_8088
        jbe     .legacy_only
        call    detect_nic_pnp      ; direct ISA PnP isolation -> g_nic_io/irq/mac
        jnc     .nic_found
.legacy_only:
        call    detect_nic          ; legacy 3Com ID-port (Tomahawk)
%else
        call    detect_nic          ; floor: native 3Com ID-port (Tomahawk) only
%endif
%endif
        jc      .nic_none           ; no card found
.nic_found:
        mov     dx, msg_nic         ; "3C509 I/O=0x"
        call    print_str
        mov     ax, [g_nic_io]
        call    print_hex16
        mov     dx, msg_irq         ; " IRQ=0x"
        call    print_str
        mov     ax, [g_nic_irq]
        call    print_hex16
        call    print_mac           ; " MAC=xx:xx:.."
        mov     dx, msg_crlf
        call    print_str

        call    validate_mac        ; reject an implausible station address before building on it --
        jc      .bad_mac            ; all-FF (off-device read, e.g. wrong /5 gen for a 3c509) / all-00 / multicast

        call    build_plan          ; per-gen Window-1 base + TX-start cmd + PIO immediates
        call    el3_init            ; bring the activated card to operational state (uses g_tx_start)
        call    phase_validate_dma  ; (>=286) test-before-trust: prove bus-master DMA or fall back to PIO
        ; report the resolved DMA decision (post-probe) on the console
        mov     dx, msg_dma
        call    print_str
        mov     dx, msg_dma_pio
        cmp     byte [g_use_dma], 0
        je      .dma_report
        mov     dx, msg_dma_on
.dma_report:
        call    print_str

        ; Phase 2: RX cache-coherency self-test (MAC internal loopback) -> g_flush_tier. On QEMU (no
        ; cache modelled) this concludes coherent -> NONE; on a non-coherent 486+ it picks WBINVD.
        call    phase_validate_coherency
        mov     dx, msg_coh
        call    print_str
        mov     dx, msg_coh_none
        cmp     byte [g_flush_tier], FLUSH_TIER_NONE
        je      .coh_report
        mov     dx, msg_coh_wbinvd
        cmp     byte [g_flush_tier], FLUSH_TIER_WBINVD
        je      .coh_report
        mov     dx, msg_coh_evict
.coh_report:
        call    print_str
        ; NC status (only when /n=<id> opted in): validated by the cold re-test, or requested-but-ineffective
        cmp     byte [g_nc_chipset], NC_CHIP_NONE
        je      .nc_noreport
        mov     dx, msg_nc_off
        cmp     byte [g_nc_effective], 0
        je      .nc_report
        mov     dx, msg_nc_eff
.nc_report:
        call    print_str
.nc_noreport:

        call    copybreak_autotune  ; RX copybreak threshold T = c_setup / a_PIO (cost model + PIT-timed probe)
        mov     dx, msg_cb
        call    print_str
        mov     ax, [g_copybreak_t]
        call    print_hex16
        mov     dx, msg_crlf
        call    print_str

        call    compose_resident    ; ax = emitted length, fills resident_image + g_off
        or      ax, ax
        jz      .fail
        mov     [g_emitted_len], ax
%ifdef CFG_DEBUG
        mov     dx, msg_emit
        call    print_str
        mov     ax, [g_emitted_len]
        call    print_hex16
%endif

        call    copy_down           ; ax = paragraphs to keep
        mov     [g_keep_para], ax

        call    install             ; hook INT 60h, free env, DOS TSR-keep (never returns)
        ; (NIC IRQ hook + ISR receiver upcall land with real 3c509 hardware)
.nic_none:
        mov     dx, msg_no_nic
        call    print_str
.fail:
        mov     ax, 0x4C01
        int     0x21
.bad_mac:
        mov     dx, msg_badmac
        call    print_str
        jmp     .fail

;------------------------------------------------------------------------------
; do_uninstall -- `3cpd /u`: find the resident driver via the INT 60h vector + the
; "PKT DRVR" signature, ask it to tear down (vendor fn 0x82 restores vectors + masks the
; IRQ and returns its PSP in BX), then free its memory block. Separate process from the
; resident instance, so freeing the resident block is safe.
;------------------------------------------------------------------------------
do_uninstall:
        mov     ax, DGROUP
        mov     ds, ax
        mov     ax, 0x3500 | PKTINT     ; get INT 60h vector -> ES:BX
        int     0x21
        ; verify "PKT DRVR" at ES:BX+3 before trusting the vector
        mov     di, bx
        add     di, 3
        mov     si, sig_pktdrvr
        mov     cx, 8
.sigcmp:
        mov     al, [si]
        cmp     al, [es:di]
        jne     .notinst
        inc     si
        inc     di
        loop    .sigcmp
        ; it's ours -- tear down, then free the resident block
        mov     ah, 0x82                ; PD_UNINSTALL -> BX = resident PSP
        int     PKTINT
        mov     es, bx
        mov     ah, 0x49                ; free the resident memory block
        int     0x21
        mov     dx, msg_uninst
        call    print_str
        mov     ax, 0x4C00
        int     0x21
.notinst:
        mov     dx, msg_notinst
        call    print_str
        mov     ax, 0x4C01
        int     0x21

;------------------------------------------------------------------------------
; detect_cpu -- full non-CPUID class ladder: 8088 / 286 / 386 / 486 / CPUID-capable.
; Sets g_cpu_class. The 8086/286 split is the 16-bit FLAGS bits 12-15 test (8088-safe);
; the 386/486/CPUID split uses the 32-bit EFLAGS AC and ID flags (only reached on 386+, so
; the floor never executes a 32-bit instruction). Finer family/feature detail needs the
; CPUID-parsing layer (lifted when the cache-coherency tier lands). ~122 bytes, cold.
;------------------------------------------------------------------------------
detect_cpu:
        pushf
        pop     ax
        mov     cx, ax              ; save original FLAGS
        and     ax, 0x0FFF          ; try to clear bits 12-15
        push    ax
        popf
        pushf
        pop     ax
        and     ax, 0xF000
        cmp     ax, 0xF000          ; stuck set -> 8086/8088
        je      .is8088
        or      cx, 0xF000          ; try to set bits 12-15
        push    cx
        popf
        pushf
        pop     ax
        and     ax, 0xF000
        jz      .is286              ; stuck clear (can't set in real mode) -> 286
        ; --- 386+ : 32-bit EFLAGS tests (unreachable on 8086/286) ---
        cpu 386
        pushfd
        pop     eax
        mov     ecx, eax
        xor     eax, 0x00040000     ; toggle AC (bit 18): 386 can't, 486+ can
        push    eax
        popfd
        pushfd
        pop     eax
        xor     eax, ecx
        test    eax, 0x00040000
        jz      .is386
        mov     eax, ecx
        xor     eax, 0x00200000     ; toggle ID (bit 21): no-CPUID can't, CPUID can
        push    eax
        popfd
        pushfd
        pop     eax
        xor     eax, ecx
        test    eax, 0x00200000
        jz      .is486
        mov     byte [g_cpu_class], CPU_CPUID
        ret
.is486:
        mov     byte [g_cpu_class], CPU_80486
        ret
.is386:
        mov     byte [g_cpu_class], CPU_80386
        ret
.is286:
        mov     byte [g_cpu_class], CPU_80286
        ret
.is8088:
        mov     byte [g_cpu_class], CPU_8088
        ret
        cpu 8086                    ; restore floor-safety check for the rest of the file

;------------------------------------------------------------------------------
; phase_validate_dma (>=286 cold phase, AFTER el3_init) -- test-before-trust (docs/04). build_plan
; tentatively set g_use_dma (3C515 + /d + >=286); here we PROVE the bus-master engine actually works
; before compose emits the DMA datapath: DMA a probe descriptor and confirm the card writes
; DN_COMPLETE back into it. Cold phase -> no ISR, so poll the descriptor STATUS, bounded by BIOS
; ticks. Pass -> keep g_use_dma. Fail (no DN_COMPLETE in time = wedged/absent engine) -> clear it,
; so compose falls back to the proven PIO floor. Mirrors dma_tx_single's descriptor + kick.
; Clobbers AX,BX,CX,DX (ES preserved). DS = DGROUP throughout.
;------------------------------------------------------------------------------
BM_TEST_LEN     equ 60                      ; probe frame size (min Ethernet payload)
phase_validate_dma:
        cmp     byte [g_use_dma], 0
        je      .pv_done                    ; PIO path: no bus-master engine to test

        push    es
        ; (cs << 4) -> dx:ax ; both descriptor and probe buffer live in CS=DGROUP (<1 MB)
        mov     bx, cs
        mov     ax, bx
        mov     cl, 4
        shl     ax, cl
        mov     dx, bx
        mov     cl, 12
        shr     dx, cl
        mov     cx, ax                      ; bx:cx = (cs << 4)
        mov     bx, dx
        ; descriptor[0].ADDR = phys(bm_test_buf); NEXT=0, STATUS=0, LEN=BM_TEST_LEN
        add     ax, bm_test_buf
        adc     dx, 0
        mov     [tx_descs + EL3_DESC_ADDR], ax
        mov     [tx_descs + EL3_DESC_ADDR + 2], dx
        xor     ax, ax
        mov     [tx_descs + EL3_DESC_NEXT], ax
        mov     [tx_descs + EL3_DESC_NEXT + 2], ax
        mov     [tx_descs + EL3_DESC_STATUS], ax
        mov     [tx_descs + EL3_DESC_STATUS + 2], ax
        mov     [tx_descs + EL3_DESC_LEN + 2], ax
        mov     word [tx_descs + EL3_DESC_LEN], BM_TEST_LEN
        ; DownListPtr <- phys(tx_descs) (two 16-bit OUTs)
        mov     ax, cx
        mov     dx, bx
        add     ax, tx_descs
        adc     dx, 0
        push    dx
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_DOWN_LIST_PTR
        out     dx, ax
        pop     ax
        add     dx, 2
        out     dx, ax
        ; kick StartDmaDown
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_START_DMA_DOWN
        out     dx, ax
        ; poll DN_COMPLETE in the descriptor, bounded by elapsed BIOS ticks
        xor     ax, ax
        mov     es, ax                      ; ES = BIOS data area
        mov     bx, [es:BIOS_TICK_COUNT]    ; start tick
.pv_wait:
        test    word [tx_descs + EL3_DESC_STATUS], EL3_DESC_DN_COMPLETE
        jnz     .pv_pass
        mov     ax, [es:BIOS_TICK_COUNT]
        sub     ax, bx
        cmp     ax, EL3_DMA_TX_TICKS
        jb      .pv_wait
        ; timeout: bus-master unproven -> fall back to the PIO floor
        mov     byte [g_use_dma], 0
        mov     byte [g_tx_ring], 0
.pv_pass:
        pop     es
.pv_done:
        ret

; bm_test_buf -- the probe frame the bus-master DMA test downloads. dest = broadcast so if it does
; reach the wire it's a well-formed broadcast, not garbage; the rest is don't-care (the test only
; proves the card DMA-read it). Cold (reclaimed after install).
bm_test_buf:    db 0xFF,0xFF,0xFF,0xFF,0xFF,0xFF
                times (BM_TEST_LEN - 6) db 0x00

;------------------------------------------------------------------------------
; phase_validate_coherency (>=286 DMA cold phase, AFTER phase_validate_dma) -- Phase 2 RX cache-
; coherency self-test (docs/17). With the bus-master engine proven, decide whether the CPU sees the
; card's RX-DMA writes WITHOUT a cache flush. Mechanism (the RX failure mode that matters most):
;   - warm a dest buffer with pattern A (the "stale" marker), in the instruction just before the DMA
;   - enable MAC internal loopback (Window 4 NET_DIAG bit 5): a bus-master TX is received back into the
;     armed RX up-descriptor instead of reaching the wire
;   - TX a frame carrying pattern B (B != A) -> the card RX-DMAs B into the dest buffer
;   - poll UP_COMPLETE, then read the dest with NO flush: == B -> COHERENT (tier NONE);
;     == A -> the CPU read a stale cached line -> NON-COHERENT (WBINVD on 486+, SW-evict on 386)
; Three trials; any stale OR a timeout -> non-coherent (conservative -- can't prove coherent, don't assume
; it). On QEMU/TCG (no cache modelled) the loopback delivers B and every trial reads fresh -> NONE: this
; is the structural verification (probe runs end-to-end, concludes coherent, no flush, no regression). The
; verdict lands in g_flush_tier; install maps it to the resident cache_flush helper. Cold; clobbers
; AX,BX,CX,DX,SI and ES (ES restored). DS = DGROUP. Leaves the card in Window 1 (el3_init's operating win).
;------------------------------------------------------------------------------
COH_BUF_LEN     equ 128                     ; RX dest capacity (small -> fits any cache; copybreak is 0 here)
COH_FRAME_LEN   equ 64                      ; loopback frame length (min Ethernet payload)
COH_TRIALS      equ 3
COH_PAT_A       equ 0xA5A5                  ; "stale" marker pre-warmed into the dest (both words)
COH_PAT_B       equ 0x5B5B                  ; "fresh" marker the card DMA-writes via loopback (both words)
phase_validate_coherency:
        mov     byte [g_flush_tier], FLUSH_TIER_NONE    ; coherent default (also the PIO answer)
        cmp     byte [g_use_dma], 0
        je      .pvc_done                               ; PIO floor: no bus-master path to protect

        push    es
        ; --- enable internal MAC loopback: Window 4, NET_DIAG |= INTERNAL_LB ---
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_SELECT_WINDOW | EL3_W4_MEDIA
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_W4_NET_DIAG
        in      ax, dx
        or      ax, EL3_NET_DIAG_INTERNAL_LB
        out     dx, ax

%ifdef CFG_FORCE_NC
        jmp     .pvc_noncoherent                        ; structural test (no cache to read stale): force the
                                                        ; non-coherent path so the opt-in NC re-test runs
%endif
        ; base verdict: COH_TRIALS loopback trials into coh_rx_buf; any stale OR timeout -> non-coherent
        mov     byte [coh_trials_left], COH_TRIALS
.pvc_loop:
        mov     di, coh_rx_buf
        call    coh_one_trial
        jc      .pvc_noncoherent
        dec     byte [coh_trials_left]
        jnz     .pvc_loop
        jmp     .pvc_cleanup                            ; all fresh -> coherent -> g_flush_tier stays NONE

.pvc_noncoherent:
        ; record the always-correct FALLBACK flush tier (the verdict if NC is unavailable/ineffective).
        ; 486+ -> WBINVD; <486 -> software-evict (deferred, docs/17). On QEMU this branch is unreachable
        ; without CFG_FORCE_NC (no cache -> the loopback always reads fresh).
        mov     byte [g_flush_tier], FLUSH_TIER_EVICT
        cmp     byte [g_cpu_class], CPU_80486
        jb      .pvc_nc
        mov     byte [g_flush_tier], FLUSH_TIER_WBINVD
.pvc_nc:
        ; --- Phase 2 step 4 (opt-in /n=<id>): try to fence a region non-cacheable and RE-TEST. The re-test
        ; uses a VIRGIN buffer (coh_nc_buf, untouched until now) so a stale cached line from the base trials
        ; can't give a false "fresh" reading (docs/13 rung 3). Fresh after marking -> NC genuinely fences the
        ; cache -> arm g_nc_effective; f_xms_configure then marks the LIVE ring NC and drops the flush. The
        ; flush stays armed here -- it is dropped only at configure, only after the ring is actually marked. ---
        cmp     byte [g_nc_chipset], NC_CHIP_NONE
        je      .pvc_cleanup
        ; --- Phase 2 step 4b GATE: chipset NC fences only help WRITE-BACK caches. The base test above flags
        ; non-coherence from the RX-READ direction (card writes, CPU reads stale), which fires identically on
        ; write-through AND write-back -- but on a write-through cache the CPU's writes reach memory at once
        ; (the card reads them fresh) so chipset NC is the WRONG tool; invalidation already suffices there.
        ; Probe the CPU-WRITE->card-READ direction to tell WB from WT. <486 can't WBINVD-probe and the 386
        ; software-evict tier is deferred (docs/17), so don't arm NC below a 486. ---
        cmp     byte [g_cpu_class], CPU_80486
        jb      .pvc_cleanup                            ; <486: no WB probe -> keep the flush, never mark NC
        call    coh_is_writeback                        ; CF=1 -> write-back (NC-eligible); CF=0 -> write-through
%ifdef CFG_FORCE_NC
        stc                                             ; structural test: the cacheless emulator probes as
                                                        ; write-through, so force the WB verdict to keep the
                                                        ; NC mark + re-test path exercised under CFG_FORCE_NC
%endif
        jnc     .pvc_cleanup                            ; write-through / no cache -> NC not the tool -> keep flush
        ; Base the NC window on coh_up_desc (the probe DESCRIPTOR the card writes UP_COMPLETE into, which
        ; coh_one_trial polls) so the re-test validates BOTH descriptor + payload coherency under NC, not
        ; just the payload. 128 KB span robustly covers coh_up_desc..coh_nc_buf even across a 64 KB boundary.
        mov     si, coh_up_desc
        call    cs_phys                                 ; dx:ax = phys(coh_up_desc)
        mov     bx, ax
        mov     cl, 10
        shr     bx, cl                                  ; bx = (phys low) >> 10
        mov     al, dl                                  ; dl = phys bits 16..19 (<1 MB -> <= 0x0F)
        xor     ah, ah
        mov     cl, 6
        shl     ax, cl                                  ; ax = bits16..19 << 6 (their weight in phys>>10)
        or      bx, ax                                  ; bx = phys >> 10 = base_kb
        and     bx, 0xFFC0                              ; align DOWN to 64 KB
        mov     cx, 128                                 ; size_kb = two 64 KB windows (covers the probe span)
        call    nc_mark_region                          ; fence it NC (CF=1 -> not encodable for this chipset)
        jc      .pvc_cleanup                            ; can't mark -> NC unavailable -> keep the flush
        mov     di, coh_nc_buf
        call    coh_one_trial                           ; RE-TEST: does the CPU now read fresh with no flush?
        pushf
        call    nc_clear_region                         ; undo the transient probe marking, pass or fail
        popf
        jc      .pvc_cleanup                            ; still stale -> NC ineffective -> keep the flush
        mov     byte [g_nc_effective], 1                ; NC works on this chipset -> configure marks ring + drops flush

.pvc_cleanup:
        ; clear loopback (Window 4 NET_DIAG &= ~INTERNAL_LB), then restore Window 1 (operating)
        mov     dx, [g_nic_io]
        add     dx, EL3_W4_NET_DIAG
        in      ax, dx
        and     ax, (~EL3_NET_DIAG_INTERNAL_LB) & 0xFFFF
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_SELECT_WINDOW | EL3_W1_OPERATING
        out     dx, ax
        pop     es
.pvc_done:
        ret

;------------------------------------------------------------------------------
; coh_one_trial -- one MAC-loopback RX-coherency trial (loopback must already be enabled). DI = dest buffer
; (>= COH_BUF_LEN). Warms [DI]=A in the instruction before the DMA, loopback-TXes B into it, polls
; UP_COMPLETE (bounded by BIOS ticks), reads [DI] with NO cache flush. CF=0 -> read fresh B (coherent);
; CF=1 -> stale A or timeout. Clobbers AX,BX,CX,DX,SI,ES; DI preserved. Cold.
;------------------------------------------------------------------------------
coh_one_trial:
        mov     word [di],     COH_PAT_A                ; warm the dest with A (the stale marker)
        mov     word [di + 2], COH_PAT_A
        mov     word [coh_tx_buf],     COH_PAT_B        ; (re)stamp the loopback source with B
        mov     word [coh_tx_buf + 2], COH_PAT_B
        mov     si, coh_tx_buf                          ; SI=src, DI=dest -> build descriptors + start the DMA
        call    coh_build_descs
        call    coh_start_dma
        ; poll UP_COMPLETE, bounded by elapsed BIOS ticks
        xor     ax, ax
        mov     es, ax
        mov     bx, [es:BIOS_TICK_COUNT]
.cot_wait:
        test    word [coh_up_desc + EL3_DESC_STATUS], EL3_DESC_UP_COMPLETE
        jnz     .cot_rxdone
        mov     ax, [es:BIOS_TICK_COUNT]
        sub     ax, bx
        cmp     ax, EL3_DMA_TX_TICKS
        jb      .cot_wait
        stc                                             ; timeout -> treat as stale (can't prove fresh)
        ret
.cot_rxdone:
        cmp     word [di], COH_PAT_B                    ; read the dest with NO flush
        jne     .cot_stale
        cmp     word [di + 2], COH_PAT_B
        jne     .cot_stale
        clc                                             ; fresh -> coherent
        ret
.cot_stale:
        stc
        ret

;------------------------------------------------------------------------------
; coh_build_descs -- build the internal-loopback descriptor pair: RX up-descriptor dest=DI (LEN=COH_BUF_LEN
; capacity), TX down-descriptor src=SI (LEN=COH_FRAME_LEN, reuses tx_descs); NEXT/STATUS=0. Does NOT touch
; the buffer contents. Preserves DI,SI; clobbers AX,BX,CX,DX. Split from coh_start_dma so the WB probe can
; WBINVD BETWEEN building the descriptors and starting the DMA (so the flush also lands the descriptors in
; memory -> the card reads them coherently on the very write-back cache being probed). Cold.
;------------------------------------------------------------------------------
coh_build_descs:
        push    di
        push    si
        mov     si, di                                  ; up-descriptor: ADDR=phys(DI)
        call    cs_phys
        mov     [coh_up_desc + EL3_DESC_ADDR], ax
        mov     [coh_up_desc + EL3_DESC_ADDR + 2], dx
        xor     ax, ax
        mov     [coh_up_desc + EL3_DESC_NEXT], ax
        mov     [coh_up_desc + EL3_DESC_NEXT + 2], ax
        mov     [coh_up_desc + EL3_DESC_STATUS], ax
        mov     [coh_up_desc + EL3_DESC_STATUS + 2], ax
        mov     word [coh_up_desc + EL3_DESC_LEN], COH_BUF_LEN
        mov     [coh_up_desc + EL3_DESC_LEN + 2], ax
        pop     si                                      ; down-descriptor (tx_descs): ADDR=phys(SI=src)
        push    si
        call    cs_phys
        mov     [tx_descs + EL3_DESC_ADDR], ax
        mov     [tx_descs + EL3_DESC_ADDR + 2], dx
        xor     ax, ax
        mov     [tx_descs + EL3_DESC_NEXT], ax
        mov     [tx_descs + EL3_DESC_NEXT + 2], ax
        mov     [tx_descs + EL3_DESC_STATUS], ax
        mov     [tx_descs + EL3_DESC_STATUS + 2], ax
        mov     word [tx_descs + EL3_DESC_LEN], COH_FRAME_LEN
        mov     [tx_descs + EL3_DESC_LEN + 2], ax
        pop     si
        pop     di
        ret

;------------------------------------------------------------------------------
; coh_start_dma -- kick the loopback: UpListPtr <- phys(coh_up_desc) + StartDmaUp, then DownListPtr <-
; phys(tx_descs) + StartDmaDown. Reads only the descriptor ADDRESSES (cs_phys, not memory) so it leaves the
; just-flushed descriptor bytes untouched. Clobbers AX,CX,DX,SI. Cold.
;------------------------------------------------------------------------------
coh_start_dma:
        mov     si, coh_up_desc                         ; arm RX
        call    cs_phys
        push    dx
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_UP_LIST_PTR
        out     dx, ax
        pop     ax
        add     dx, 2
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_START_DMA_UP
        out     dx, ax
        mov     si, tx_descs                            ; kick TX (loopback)
        call    cs_phys
        push    dx
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_DOWN_LIST_PTR
        out     dx, ax
        pop     ax
        add     dx, 2
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_START_DMA_DOWN
        out     dx, ax
        ret

;------------------------------------------------------------------------------
; coh_is_writeback -- WRITE-BACK vs write-through discriminator (486+; WBINVD available). Chipset NC fences
; only help write-back caches: on a write-through cache the CPU's writes reach memory immediately so the bus
; master reads them fresh, and chipset NC is the wrong tool (invalidation already suffices). Probe the
; CPU-WRITE->card-READ direction (the base test only probes card-WRITE->CPU-READ, which is stale on BOTH WT
; and WB):
;   - build the descriptors, write OLD into the (cached) src, then WBINVD -> memory holds the descriptors
;     AND src=OLD, cache clean
;   - write NEW into src with NO flush -> WB: cache=NEW dirty, memory[src] STILL OLD; WT: memory[src]=NEW
;   - loopback src -> a VIRGIN dest (the card DMA-reads memory[src]); read the dest (virgin first-touch is a
;     fresh memory read): dest == OLD -> the card saw stale memory -> WRITE-BACK (CF=1, NC-eligible)
;                         dest == NEW -> the card saw fresh memory -> write-through / no cache (CF=0)
; coh_wb_dst is 32-aligned + untouched after the WBINVD so its first cache line can't be pre-loaded (which
; would fake a fresh read). The settle poll is non-coherent on a cached system -> it just bounds a delay; the
; verdict is the virgin dest. On the cacheless emulator memory always = NEW -> CF=0 (correctly not-WB; the
; CFG_FORCE_NC call site overrides to keep the NC structural test alive). Clobbers AX,BX,CX,DX,SI,DI,ES. Cold.
;------------------------------------------------------------------------------
WB_PAT_OLD      equ 0x0F0F                              ; pre-flush memory value (seen iff writes sit dirty in cache)
WB_PAT_NEW      equ 0xF0F0                              ; post-flush value written WITHOUT a flush
coh_is_writeback:
        mov     di, coh_wb_dst                          ; dest = virgin; src = coh_wb_src
        mov     si, coh_wb_src
        call    coh_build_descs                         ; build BEFORE the WBINVD so the flush lands them too
        mov     word [coh_wb_src],     WB_PAT_OLD       ; src = OLD (cached, dirty)
        mov     word [coh_wb_src + 2], WB_PAT_OLD
        db      0x0F, 0x09                              ; WBINVD: descriptors + src(OLD) -> memory; invalidate
        mov     word [coh_wb_src],     WB_PAT_NEW       ; src = NEW, NO flush (WB: memory stays OLD; WT: -> NEW)
        mov     word [coh_wb_src + 2], WB_PAT_NEW
        call    coh_start_dma                           ; card DMA-reads memory[src] -> virgin dest
        xor     ax, ax
        mov     es, ax
        mov     bx, [es:BIOS_TICK_COUNT]
.wb_wait:
        test    word [coh_up_desc + EL3_DESC_STATUS], EL3_DESC_UP_COMPLETE
        jnz     .wb_settled
        mov     ax, [es:BIOS_TICK_COUNT]
        sub     ax, bx
        cmp     ax, EL3_DMA_TX_TICKS
        jb      .wb_wait
.wb_settled:
        cmp     word [coh_wb_dst], WB_PAT_OLD           ; virgin -> fresh memory read; OLD -> WRITE-BACK
        jne     .wb_through
        stc                                             ; write-back -> NC-eligible
        ret
.wb_through:
        clc                                             ; write-through / no cache -> NC not the tool
        ret

; cs_phys -- 20-bit physical address of CS:si -> dx:ax (dx = top 4 bits). Clobbers CX only. Cold helper.
cs_phys:
        mov     ax, cs
        mov     cl, 4
        shl     ax, cl
        mov     dx, cs
        mov     cl, 12
        shr     dx, cl
        add     ax, si
        adc     dx, 0
        ret

; coherency-probe cold scratch (reclaimed after install): a loopback TX source carrying pattern B (its
; down-list reuses tx_descs), a dedicated RX up-descriptor, and the RX dest the card DMA-writes into.
coh_tx_buf:      times COH_FRAME_LEN db 0
coh_trials_left: db 0
coh_up_desc:     times EL3_DESC_SIZE db 0
coh_rx_buf:      times COH_BUF_LEN db 0
coh_nc_buf:      times COH_BUF_LEN db 0          ; VIRGIN buffer for the NC re-test (untouched until then, so no
                                                ; stale cached line from the base trials can fake a "fresh" read)
; WB-discriminator buffers (coh_is_writeback): the card reads coh_wb_src (CPU-written) and RX-DMAs into the
; VIRGIN coh_wb_dst. 32-byte aligned so coh_wb_dst's first cache line is never shared with coh_wb_src -- else
; writing coh_wb_src=NEW would pre-cache coh_wb_dst's line and fake a "fresh" read on a write-back cache.
        alignb 32
coh_wb_src:      times COH_FRAME_LEN db 0
        alignb 32
coh_wb_dst:      times COH_BUF_LEN db 0

; detect_nic / id_read_eeprom / io_delay -- the real 3C509B ISA probe + activation.
%include "el3_probe.asm"

; el3_init -- operational bring-up of the activated card (MAC, media, RX/TX enable).
%include "el3_init.asm"

; copybreak_autotune -- compute the RX copybreak threshold T (cost model + PIT-timed PIO probe).
%include "copybreak.asm"

%ifdef CFG_PNP
; detect_nic_pnp -- direct ISA PnP isolation (3C515 / PnP-mode 3C509B). >=286-gated by caller.
%include "isapnp.asm"
%endif

; install -- hook INT 60h + NIC IRQ, enable card int, free environment, DOS TSR-keep.
%include "install.asm"

;------------------------------------------------------------------------------
; build_plan -- resolve the per-generation hardware parameters and hand the composer its
; immediates. Two generation-dependent values: the Window-1 register base (3C509 at io_base,
; Corkscrew at io_base+0x10) and the SET_TX_START command (3C509 early-start vs 3C515
; store-and-forward). The PIO datapath FIFO immediate is the Window-1 base.
;------------------------------------------------------------------------------
build_plan:
        mov     ax, EL3_W1_DELTA_3C509                       ; default: 3C509/B layout
        cmp     byte [g_nic_gen], 0
        je      .gen_done
        mov     ax, EL3_W1_DELTA_VORTEX                      ; 3C515: registers relocated +0x10
.gen_done:
        add     ax, [g_nic_io]
        mov     [g_w1_base], ax             ; Window-1 data-register base (FIFO/status/free)
        ; PIO TX uses early-start on BOTH generations: the wire overlaps the FIFO fill, keeping a
        ; slow CPU near wire rate at 10 Mbit. The 3C515's former store-and-forward threshold (1536)
        ; exceeds a standard frame, so the wire never early-started -- serialized fill+transmit,
        ; ~16x slower at 286/10M (598 vs 9717 kbit/s). 100 Mbit uses DMA (PIO@100 is impractical),
        ; so SF bought nothing here; and DMA TX bypasses this FIFO threshold entirely.
        mov     bx, EL3_CMD_SET_TX_START | EL3_TX_START_THRESH
        mov     [g_tx_start], bx            ; precomputed SET_TX_START command
        mov     [g_plan_rx_imm], ax         ; PIO datapath FIFO immediate = Window-1 base
        mov     [g_plan_tx_imm], ax
        ; --- resolve bus-master single-transfer TX DMA: /d AND 3C515 AND >=286 (else PIO floor) ---
        mov     byte [g_use_dma], 0
        cmp     byte [g_want_dma], 0
        je      .dma_resolved
        cmp     byte [g_nic_gen], 1             ; Corkscrew (3C515) only -- has the bus-master engine
        jne     .dma_resolved
        cmp     byte [g_cpu_class], CPU_80286   ; >=286: real mode, phys = seg*16+off, 24-bit ISA-safe
        jb      .dma_resolved
        mov     byte [g_use_dma], 1
.dma_resolved:
        ; Zero-copy async TX ring (AH=0xF1) is available on ANY bus-master config (>=286): dma_tx_async
        ; is 8086-clean and does no per-frame copy, so the 286 limitation (no movsd) doesn't apply.
        mov     al, [g_use_dma]
        mov     [g_async], al
        ; send_pkt's resident DMA path: 386+ uses the non-blocking COPY ring (movsd slot copy); a 286
        ; can't hide that per-frame copy (no movsd), so its send_pkt uses the blocking zero-copy
        ; single-transfer instead -- ~+47% at 100 Mbit (28668 vs 19570 kbit/s). (Async is separate.)
        mov     byte [g_tx_ring], 0
        cmp     byte [g_cpu_class], CPU_80386
        jb      .ring_resolved
        mov     byte [g_tx_ring], 1
.ring_resolved:
        ; --- resolve FDDI-sized large frames: /j AND 3C515 (else standard Ethernet). Sets the RX
        ;     length mask to the 13-bit Corkscrew field so a >2047 B frame's length isn't truncated.
        ;     el3_init sets allowLargePackets in MacControl when g_use_large. ---
        mov     byte [g_use_large], 0
        mov     word [g_rx_len_mask], 0x07FF     ; default: standard Ethernet (11-bit-safe)
        cmp     byte [g_want_large], 0
        je      .large_resolved
        cmp     byte [g_nic_gen], 1              ; Corkscrew (3C515) only
        jne     .large_resolved
        mov     byte [g_use_large], 1
        mov     word [g_rx_len_mask], 0x1FFF     ; 13-bit length field (FDDI-sized RX)
.large_resolved:
        call    dma_v86_forbid_check    ; V86 + no VDS -> force the PIO floor (dma.h DMA_POLICY_FORBID)
        ret

;------------------------------------------------------------------------------
; dma_v86_forbid_check -- under a paging memory manager (V86) WITHOUT VDS we cannot get a safe bus-master
; physical (seg<<4 is a lie when low memory is remapped, and there's no VDS to translate/lock), so fall
; back to the PIO floor -- dma.h's DMA_POLICY_FORBID. Real mode keeps DMA (seg<<4 valid). V86 *with* VDS
; keeps DMA too: TX seg<<4 correctness is then proven empirically by phase_validate_dma (its descriptor
; poll mismatches under a remapping map -> timeout -> PIO) and the RX conv ring gets the true physical from
; the VDS-locking stack (XMS_POLICY_COMMONBUF). Cold; clobbers AX, ES. Only reached on >=286 (SMSW).
;------------------------------------------------------------------------------
dma_v86_forbid_check:
        cmp     byte [g_use_dma], 0
        je      .dvf_done               ; already PIO -> nothing to forbid
        push    es
        db      0x0F, 0x01, 0xE0        ; SMSW AX (bytes: legal in V86, 286+; the DMA path is >=286)
        test    ax, 1                   ; CR0.PE: 1 = a protected-mode host is paging us (V86); 0 = real mode
        jz      .dvf_keep               ; real mode -> seg<<4 is the bus address -> keep DMA
        xor     ax, ax
        mov     es, ax
        test    byte [es:0x047B], 0x20  ; BIOS data 0040:007Bh bit 5 = VDS available
        jnz     .dvf_keep               ; V86 + VDS -> keep DMA (phys proven by the bus-master test + stack VDS)
        mov     byte [g_use_dma], 0     ; V86 + no VDS -> can't address safely -> PIO floor
        mov     byte [g_async], 0
        mov     byte [g_tx_ring], 0
.dvf_keep:
        pop     es
.dvf_done:
        ret

;------------------------------------------------------------------------------
; compose_resident -- select + stitch + patch the planned fragments into resident_image.
; Records each fragment's landing offset in g_off[]. 8088-clean (movsb/stosw/loops).
; out: AX = emitted length (0 on missing fragment / over budget).
;------------------------------------------------------------------------------
compose_resident:
        ; g_off[] = 0xFFFF
        mov     di, g_off
        mov     cx, FRAG__COUNT
        mov     ax, 0xFFFF
        rep     stosw                   ; ES:DI (= DGROUP)

        mov     word [g_pos], 0
        mov     word [g_planptr], g_plan
        mov     word [g_step], G_PLAN_N
.step:
        mov     si, [g_planptr]
        mov     al, [si]                ; frag id
        mov     [g_curid], al
        inc     si
        mov     ax, [si]                ; imm0
        mov     [g_imm0], ax
        add     si, 2
        mov     [g_planptr], si

        mov     al, [g_curid]
        call    frag_lookup             ; -> DI = entry, CF=1 if none
        jc      .fail

        ; g_off[id] = pos
        mov     bl, [g_curid]
        xor     bh, bh
        shl     bx, 1
        mov     ax, [g_pos]
        mov     [g_off + bx], ax

        ; copy fragment bytes: resident_image[pos..] = entry.bytes[0..len)
        mov     cx, [di + 4]            ; len
        mov     si, [di + 6]            ; src ptr
        push    di
        mov     di, resident_image
        add     di, [g_pos]
        rep     movsb                   ; DS:SI -> ES:DI
        pop     di

        ; apply immediate patches (floor: all PATCH_IMM16 = io_base)
        xor     ch, ch
        mov     cl, [di + 2]            ; n_patches
        jcxz    .nopatch
        mov     si, [di + 8]            ; patch table ptr
.patch:
        mov     bx, [si]                ; patch.offset (within fragment)
        add     bx, [g_pos]
        mov     ax, [g_imm0]
        mov     [resident_image + bx], ax
        add     si, PATCH_ENTRY_SIZE
        loop    .patch
.nopatch:
        mov     ax, [di + 4]            ; pos += len
        add     [g_pos], ax

        dec     word [g_step]
        jnz     .step

        mov     ax, [g_pos]
        ret
.fail:
        xor     ax, ax
        ret

;------------------------------------------------------------------------------
; frag_lookup -- find the best fragment for (id=AL, class=g_cpu_class): matching id with
; the highest cpu_min that is <= the detected class. out: DI = entry, CF=0; CF=1 if none.
; clobbers BX, CX, DX (and DI).
;------------------------------------------------------------------------------
frag_lookup:
        mov     di, g_frags
        mov     cx, FRAG_TABLE_N
        xor     bx, bx                  ; bx = best entry (0 = none yet)
        xor     dl, dl                  ; dl = best cpu_min
.fl_loop:
        cmp     [di], al                ; entry.id == id?
        jne     .fl_next
        mov     dh, [di + 1]            ; entry.cpu_min
        cmp     dh, [g_cpu_class]
        ja      .fl_next                ; cpu_min > class -> not emittable
        or      bx, bx
        jz      .fl_take                ; first match
        cmp     dh, dl
        jbe     .fl_next                ; not a higher cpu_min than current best
.fl_take:
        mov     bx, di
        mov     dl, dh
.fl_next:
        add     di, FRAG_ENTRY_SIZE
        loop    .fl_loop

        or      bx, bx
        jz      .fl_none
        mov     di, bx
        clc
        ret
.fl_none:
        stc
        ret

;------------------------------------------------------------------------------
; copy_down -- floor: the image was composed in place in resident_image (no relocs in the
; PIO floor fragments), so this just reports the size in paragraphs. Real packing + reloc
; fixups arrive with cross-fragment references. in: AX = emitted len; out: AX = paragraphs.
;------------------------------------------------------------------------------
copy_down:
        add     ax, 15
        mov     cl, 4
        shr     ax, cl                  ; ceil(len / 16)
        ret

;------------------------------------------------------------------------------
; Diagnostic print helpers (COLD; DOS INT 21h). Clobber AX/CX/DX freely.
;------------------------------------------------------------------------------
print_str:                              ; DS:DX -> '$'-terminated string
        mov     ah, 9
        int     0x21
        ret
print_char:                             ; AL = character
        mov     dl, al
        mov     ah, 2
        int     0x21
        ret
print_hex16:                            ; AX = value -> 4 hex digits
        push    ax
        mov     al, ah
        call    print_hex8
        pop     ax
        call    print_hex8
        ret
print_hex8:                             ; AL = byte -> 2 hex digits
        push    ax
        mov     cl, 4
        shr     al, cl                  ; high nibble
        call    print_nib
        pop     ax                      ; low nibble (print_nib masks)
        call    print_nib
        ret
print_nib:                              ; AL low nibble -> hex char
        and     al, 0x0F
        add     al, '0'
        cmp     al, '9'
        jbe     .e
        add     al, 7                   ; 'A'..'F'
.e:
        mov     dl, al
        mov     ah, 2
        int     0x21
        ret
print_mac:                              ; " MAC=" + g_mac[0..5] as hex
        mov     dx, msg_mac
        call    print_str
        mov     si, g_mac
        mov     cx, 6
.pm:
        push    cx
        lodsb
        call    print_hex8
        pop     cx
        loop    .pm
        ret

;------------------------------------------------------------------------------
; validate_mac -- sanity-check the station address in g_mac[0..5] before the driver
; builds the resident image on it. A read from an unmapped/off-device window returns
; 0xFF on every byte (the failure mode behind a wrong /5 gen on a 3C509: el3_load_mac_io
; lands the MAC read at the +0x2000 alias, off the card), and an EEPROM that never
; loaded reads back all-00. A real station address is also always unicast (bit 0 of the
; first byte clear). Reject all three. 8088-clean. out: CF=1 invalid, CF=0 plausible.
; Clobbers AX, CX, SI (DL preserved via push).
;------------------------------------------------------------------------------
validate_mac:
        test    byte [g_mac], 1         ; I/G bit set -> multicast/broadcast, not a station addr
        jnz     .bad
        push    dx
        mov     si, g_mac
        mov     cx, 6
        mov     ah, 0xFF                ; AND-accumulator: stays 0xFF iff every byte is 0xFF
        xor     dl, dl                  ; OR-accumulator:  stays 0x00 iff every byte is 0x00
.vm:
        lodsb
        and     ah, al
        or      dl, al
        loop    .vm
        cmp     ah, 0xFF                ; all bytes 0xFF -> off-device / unmapped read
        je      .bad_pop
        or      dl, dl                  ; all bytes 0x00 -> EEPROM never loaded
        jz      .bad_pop
        pop     dx
        clc
        ret
.bad_pop:
        pop     dx
.bad:
        stc
        ret

;------------------------------------------------------------------------------
; parse_hex16 / parse_dec16 -- read a number from the command tail (ES:SI), stopping at the
; first non-digit. out: BX = value, SI advanced past the digits. Clobbers AX, CX (and DX/dec).
;------------------------------------------------------------------------------
parse_hex16:
        xor     bx, bx
.ph:    mov     al, [es:si]
        cmp     al, '0'
        jb      .ph_done
        cmp     al, '9'
        jbe     .ph_d09
        or      al, 0x20                ; tolower
        cmp     al, 'a'
        jb      .ph_done
        cmp     al, 'f'
        ja      .ph_done
        sub     al, 'a' - 10            ; 'a'..'f' -> 10..15
        jmp     .ph_acc
.ph_d09:
        sub     al, '0'                 ; '0'..'9' -> 0..9
.ph_acc:
        mov     cl, 4
        shl     bx, cl                  ; bx *= 16
        xor     ah, ah
        add     bx, ax
        inc     si
        jmp     .ph
.ph_done:
        ret

parse_dec16:
        xor     bx, bx
.pd:    mov     al, [es:si]
        cmp     al, '0'
        jb      .pd_done
        cmp     al, '9'
        ja      .pd_done
        sub     al, '0'
        mov     cx, bx                  ; bx = bx*10 + digit  (10x = ((4x)+x)*2)
        shl     bx, 1
        shl     bx, 1
        add     bx, cx
        shl     bx, 1
        xor     ah, ah
        add     bx, ax
        inc     si
        jmp     .pd
.pd_done:
        ret
