; start.asm -- 3com-pktdrv cold entry + JIT composer (fully assembly, no C runtime).
;
; The driver is a single self-specializing TSR (docs/02). At load, COLD code detects the
; machine, then COMPOSES the hot path from position-independent fragments (build/frags_asm.inc,
; generated by tools/mkfrag.py from src/asm/frag/*.asm), baking decisions in as immediates.
; copy-down then packs the emitted image and DOS-keeps it; everything here is reclaimed.
;
; This file is the cold orchestration + composer. It must itself be 8088-clean (it runs on
; a 5150). The emitted hot path is the fragments, not this code.
;
; Build: nasm -f obj -> wlink (system dos). Entry point is ..start. No C, no C library.

cpu 8086
bits 16

%include "codegen.inc"

;==============================================================================
; DATA (initialized) -- fragment palette, plan template
;==============================================================================
segment _DATA public class=DATA use16

%include "frags_asm.inc"        ; f_*[], *_patches[], g_frags[], FRAG_TABLE_N

; The emit plan for a 3C509B (PIO floor): the fragment ids to compose, each followed by its
; immediate-0 (io_base for the PIO datapath steps; 0 for the rest). build_plan() fills the
; io_base slots from the detected NIC. Layout per step: db id ; dw imm0  (3 bytes).
g_plan:
    db FRAG_API_DISPATCH
    dw 0
    db FRAG_ISR_ENTRY
    dw 0
    db FRAG_RX_PIO
g_plan_rx_imm:
    dw 0
    db FRAG_TX_PIO
g_plan_tx_imm:
    dw 0
    db FRAG_ISR_EOI
    dw 0
G_PLAN_N        equ 5
PLAN_STEP_SIZE  equ 3

;==============================================================================
; BSS (uninitialized) -- runtime state + the emit destination
;==============================================================================
segment _BSS public class=BSS use16

g_cpu_class:    resb 1          ; CPU_8088 .. CPU_P6 (set by detect_cpu)
                resb 1
g_nic_io:       resw 1          ; detected 3C509B I/O base
g_emitted_len:  resw 1
g_keep_para:    resw 1

; composer scratch
g_pos:          resw 1          ; current write offset into resident_image
g_planptr:      resw 1
g_step:         resw 1
g_imm0:         resw 1
g_curid:        resb 1
                resb 1

; entry offsets of each emitted fragment (0xFFFF if not emitted); install reads
; g_off[FRAG_API_DISPATCH] and g_off[FRAG_ISR_ENTRY].
g_off:          resw FRAG__COUNT

; the composed hot image (copy-down packs it; DOS-keeps up to here)
resident_image: resb 512

;==============================================================================
; STACK -- in DGROUP so SS == DS (small model). The cold composer's working stack;
; the resident TSR sets up its own stack when install lands.
;==============================================================================
segment _STACK stack class=STACK use16
        resb 1024

;==============================================================================
; CODE
;==============================================================================
group DGROUP _DATA _BSS _STACK
segment _TEXT public class=CODE use16

..start:
        mov     ax, DGROUP
        mov     ds, ax
        mov     es, ax              ; composer uses ES:DI for the emit destination

        call    detect_cpu          ; -> g_cpu_class

        ; --- 5150 short-circuit -------------------------------------------------
        ; On an 8088/8086 the DMA capability axis collapses to PIO: no protected mode,
        ; no >1 MB / XMS, no bus-master, no VMM. So we skip the entire test-before-trust
        ; and environment machinery (busmaster test, cache-coherency tier, VDS/V86 probe,
        ; PCI/EISA/MCA/PCMCIA bus probers) and take the floor path straight to the PIO
        ; compose. On >=286 those cold phases run (added as the ladder is climbed).
        cmp     byte [g_cpu_class], CPU_8088
        jbe     .floor
        call    phase_platform_probe    ; (>=286) V86/VDS/memory tiers      [stub]
        call    phase_validate_dma      ; (>=286) busmaster test + cache    [stub]
.floor:
        call    detect_nic          ; -> g_nic_io (floor: 3C509B probe)
        call    build_plan          ; copy io_base into the plan's PIO steps

        call    compose_resident    ; ax = emitted length, fills resident_image + g_off
        or      ax, ax
        jz      .fail
        mov     [g_emitted_len], ax

        call    copy_down           ; ax = paragraphs to keep
        mov     [g_keep_para], ax

        ; TODO(next): install INT 60h + NIC IRQ from g_off[], then DOS TSR-keep.
        ; Deferred while the API/ISR fragments are stubs -- installing a non-functional
        ; INT 60h handler is worse than not installing. Terminate cleanly for now.
        mov     ax, 0x4C00
        int     0x21
.fail:
        mov     ax, 0x4C01
        int     0x21

;------------------------------------------------------------------------------
; detect_cpu -- classify 8086/8088 vs 286 vs 386+ via the FLAGS 12-15 test.
; 8088-safe (no push-immediate). Sets g_cpu_class. Coarse by design: the floor only
; needs 8088 vs >=286; finer 486/Pentium/CPUID detail is added with their fragments.
;------------------------------------------------------------------------------
detect_cpu:
        pushf
        pop     ax
        mov     cx, ax              ; save original FLAGS
        and     ax, 0x0FFF          ; try to clear bits 12-15
        push    ax
        popf
        pushf
        pop     ax
        and     ax, 0xF000
        cmp     ax, 0xF000          ; stuck high? -> 8086/8088
        je      .is8088
        or      cx, 0xF000          ; try to set bits 12-15
        push    cx
        popf
        pushf
        pop     ax
        and     ax, 0xF000
        jz      .is286              ; stuck low -> 286
        mov     byte [g_cpu_class], CPU_80386   ; settable -> 386+ (coarse)
        ret
.is286:
        mov     byte [g_cpu_class], CPU_80286
        ret
.is8088:
        mov     byte [g_cpu_class], CPU_8088
        ret

;------------------------------------------------------------------------------
; phase stubs (>=286 cold phases; real logic lands as the ladder is climbed)
;------------------------------------------------------------------------------
phase_platform_probe:
        ret
phase_validate_dma:
        ret

;------------------------------------------------------------------------------
; detect_nic -- floor: assume a 3C509B at a default I/O base (real ID-port isolation
; + EEPROM/MAC read land next). Sets g_nic_io.
;------------------------------------------------------------------------------
detect_nic:
        mov     word [g_nic_io], 0x300
        ret

;------------------------------------------------------------------------------
; build_plan -- the HAL hands the composer the NIC's immediates: io_base into the PIO
; datapath steps. (Equivalent of the old c509b_emit_plan.)
;------------------------------------------------------------------------------
build_plan:
        mov     ax, [g_nic_io]
        mov     [g_plan_rx_imm], ax
        mov     [g_plan_tx_imm], ax
        ret

;------------------------------------------------------------------------------
; compose_resident -- select + stitch + patch the planned fragments into resident_image.
; Records each fragment's landing offset in g_off[]. 8088-clean (movsb/stosw/loops).
; out: AX = emitted length (0 on missing fragment / over budget).
;------------------------------------------------------------------------------
compose_resident:
        ; g_off[] = 0xFFFF
        mov     di, g_off
        mov     cx, FRAG__COUNT
        mov     ax, 0xFFFF
        rep     stosw                   ; ES:DI (= DGROUP)

        mov     word [g_pos], 0
        mov     word [g_planptr], g_plan
        mov     word [g_step], G_PLAN_N
.step:
        mov     si, [g_planptr]
        mov     al, [si]                ; frag id
        mov     [g_curid], al
        inc     si
        mov     ax, [si]                ; imm0
        mov     [g_imm0], ax
        add     si, 2
        mov     [g_planptr], si

        mov     al, [g_curid]
        call    frag_lookup             ; -> DI = entry, CF=1 if none
        jc      .fail

        ; g_off[id] = pos
        mov     bl, [g_curid]
        xor     bh, bh
        shl     bx, 1
        mov     ax, [g_pos]
        mov     [g_off + bx], ax

        ; copy fragment bytes: resident_image[pos..] = entry.bytes[0..len)
        mov     cx, [di + 4]            ; len
        mov     si, [di + 6]            ; src ptr
        push    di
        mov     di, resident_image
        add     di, [g_pos]
        rep     movsb                   ; DS:SI -> ES:DI
        pop     di

        ; apply immediate patches (floor: all PATCH_IMM16 = io_base)
        xor     ch, ch
        mov     cl, [di + 2]            ; n_patches
        jcxz    .nopatch
        mov     si, [di + 8]            ; patch table ptr
.patch:
        mov     bx, [si]                ; patch.offset (within fragment)
        add     bx, [g_pos]
        mov     ax, [g_imm0]
        mov     [resident_image + bx], ax
        add     si, PATCH_ENTRY_SIZE
        loop    .patch
.nopatch:
        mov     ax, [di + 4]            ; pos += len
        add     [g_pos], ax

        dec     word [g_step]
        jnz     .step

        mov     ax, [g_pos]
        ret
.fail:
        xor     ax, ax
        ret

;------------------------------------------------------------------------------
; frag_lookup -- find the best fragment for (id=AL, class=g_cpu_class): matching id with
; the highest cpu_min that is <= the detected class. out: DI = entry, CF=0; CF=1 if none.
; clobbers BX, CX, DX (and DI).
;------------------------------------------------------------------------------
frag_lookup:
        mov     di, g_frags
        mov     cx, FRAG_TABLE_N
        xor     bx, bx                  ; bx = best entry (0 = none yet)
        xor     dl, dl                  ; dl = best cpu_min
.fl_loop:
        cmp     [di], al                ; entry.id == id?
        jne     .fl_next
        mov     dh, [di + 1]            ; entry.cpu_min
        cmp     dh, [g_cpu_class]
        ja      .fl_next                ; cpu_min > class -> not emittable
        or      bx, bx
        jz      .fl_take                ; first match
        cmp     dh, dl
        jbe     .fl_next                ; not a higher cpu_min than current best
.fl_take:
        mov     bx, di
        mov     dl, dh
.fl_next:
        add     di, FRAG_ENTRY_SIZE
        loop    .fl_loop

        or      bx, bx
        jz      .fl_none
        mov     di, bx
        clc
        ret
.fl_none:
        stc
        ret

;------------------------------------------------------------------------------
; copy_down -- floor: the image was composed in place in resident_image (no relocs in the
; PIO floor fragments), so this just reports the size in paragraphs. Real packing + reloc
; fixups arrive with cross-fragment references. in: AX = emitted len; out: AX = paragraphs.
;------------------------------------------------------------------------------
copy_down:
        add     ax, 15
        mov     cl, 4
        shr     ax, cl                  ; ceil(len / 16)
        ret
