; start.asm -- 3com-pktdrv cold entry + JIT composer (fully assembly, no C runtime).
;
; The driver is a single self-specializing TSR (docs/02). At load, COLD code detects the
; machine, then COMPOSES the hot path from position-independent fragments (build/frags_asm.inc,
; generated by tools/mkfrag.py from src/asm/frag/*.asm), baking decisions in as immediates.
; copy-down then packs the emitted image and DOS-keeps it; everything here is reclaimed.
;
; This file is the cold orchestration + composer. It must itself be 8088-clean (it runs on
; a 5150). The emitted hot path is the fragments, not this code.
;
; Build: nasm -f obj -> wlink (system dos). Entry point is ..start. No C, no C library.

cpu 8086
bits 16

%include "codegen.inc"
; Shared EL3 register constants (guarded; also pulled by the probe). build_plan needs them
; to compute the per-generation Window-1 base + TX-start command.
%include "el3_core.inc"
; Corkscrew (3C515) delta: bus-master DMA register block + descriptor layout (guarded; also
; pulled by isapnp). The resident TX DMA paths + the descriptor/ring reservations need these.
%include "el3_corkscrew.inc"
; Proprietary RX checksum-offload vendor extension (AH=0xF2) constants.
%include "rx_cksum.inc"

;==============================================================================
; DATA (initialized) -- fragment palette, plan template
;==============================================================================
segment _DATA public class=DATA use16

%include "frags_asm.inc"        ; f_*[], *_patches[], g_frags[], FRAG_TABLE_N

; The emit plan for a 3C509B (PIO floor): only the DATAPATH fragments are emitted -- the
; API dispatch and ISR are static resident code (resident.asm/isr.asm), which call the
; emitted TX/RX via g_off[]. Each step: db id ; dw imm0 (io_base, filled by build_plan).
g_plan:
    db FRAG_RX_PIO
g_plan_rx_imm:
    dw 0
    db FRAG_TX_PIO
g_plan_tx_imm:
    dw 0
G_PLAN_N        equ 2
PLAN_STEP_SIZE  equ 3

; diagnostic strings ($-terminated for INT 21h AH=09h)
msg_banner  db '3com-pktdrv floor (3C509 packet driver)', 13, 10, '$'
msg_cpu     db 'CPU class=', '$'
msg_nic     db 13, 10, '3C509 I/O=0x', '$'
msg_irq     db ' IRQ=0x', '$'
msg_mac     db ' MAC=', '$'
msg_no_nic  db 13, 10, 'No 3C509 found', 13, 10, '$'
msg_badmac  db 'ERROR: invalid station MAC (all-FF/all-00/multicast) -- wrong card gen?', 13, 10
            db '       (/5 selects 3C515 EEPROM at +0x2000; omit it for a 3C509)', 13, 10, '$'
msg_crlf    db 13, 10, '$'
msg_dma     db 'DMA=', '$'
msg_dma_on  db 'ON', 13, 10, '$'
msg_dma_pio db 'PIO', 13, 10, '$'
msg_dma_pio_nc db 'PIO (non-coherent, no safe flush)', 13, 10, '$'
msg_cb      db 'COPYBREAK T=0x', '$'
msg_coh        db 'CACHE FLUSH=', '$'           ; Phase 2 RX coherency verdict report
msg_coh_none   db 'NONE (coherent)', 13, 10, '$'
msg_coh_wbinvd db 'WBINVD (non-coherent)', 13, 10, '$'
msg_coh_nosafe db 'NONE (non-coherent, no safe flush)', 13, 10, '$'
msg_nc_eff     db 'NC=validated (applied at CONFIGURE: CONV/COMMONBUF v2 on the 386+ ring)', 13, 10, '$'
msg_nc_off     db 'NC=requested, not effective (flush kept)', 13, 10, '$'

; uninstall (`3cpd /u`)
sig_pktdrvr db 'PKT DRVR'                       ; resident signature (handler + 3); 8 bytes
msg_uninst  db 13, 10, '3com-pktdrv uninstalled', 13, 10, '$'
msg_notinst db 13, 10, '3com-pktdrv not installed', 13, 10, '$'

%ifdef CFG_FAKENIC
fake_mac    db 0x02, 0x60, 0x8C, 0x11, 0x22, 0x33   ; test MAC (3Com OUI 00:60:8C)
%endif

%ifdef CFG_DEBUG
msg_dbgon   db '[debug build]', 13, 10, '$'
msg_eeprod  db 13, 10, 'EEPROM prod=0x', '$'
msg_eeid    db ' mfg=0x', '$'
msg_emit    db 'emitted=0x', '$'
msg_keep    db ' resident para=0x', '$'
msg_inst    db 13, 10, 'INSTALLED: INT 60h, IRQ vec=0x', '$'
%endif

;==============================================================================
; BSS -- COLD scratch only (above resident_end, reclaimed after install).
;==============================================================================
segment _BSS public class=BSS use16

g_cpu_class:    resb 1          ; CPU_8088 .. CPU_CPUID (set by detect_cpu)
g_nic_gen:      resb 1          ; detected generation: 0 = Tomahawk (3C509/B), 1 = Corkscrew (3C515)
g_manual:       resb 1          ; 1 = manual /b= I/O base given -> skip the ID-port probe
g_force8:       resb 1          ; 1 = /8 given -> force the 8088-class (8-bit byte-loop) datapath
g_force286:     resb 1          ; 1 = /2 given -> force the 286-class datapath (16-bit PIO + single-transfer DMA)
g_want_dma:     resb 1          ; 1 = /d given -> request bus-master TX DMA (resolved in build_plan)
g_want_large:   resb 1          ; 1 = /j given -> request FDDI-sized large frames (gated to 3C515)
g_want_v86trust: resb 1         ; 1 = /v given -> trust the V86 host (EMM386/JEMM386) to emulate WBINVD
g_wbinvd_ok:    resb 1          ; 1 = WBINVD may run: 486+ AND (real mode OR /v). Set in dma_v86_forbid_check
g_coh_nosafe:   resb 1          ; 1 = the coherency probe found a non-coherent cache with no safe flush -> PIO
g_vds_cold_held: resb 1         ; 1 = cold_dds holds the VDS lock on the cold probe span (V86)
                alignb 2
cold_dds:       resb 16         ; VDS DDS for the cold probe span [bm_test_buf, coh_probe_end)
nc_area_dds:    resb 16         ; VDS DDS for the NC re-test probe area (V86 + /v only)
nc_area_seg:    resw 1          ; NC re-test probe area segment (offset 0) -- 512 B at the top of a 64 KB block
nc_area_phys:   resd 1          ; its physical address (= seg << 4; VDS-proven under V86)
tail_end:       resw 1          ; PSP command-tail end offset (cold arg scan)
g_emitted_len:  resw 1
g_keep_para:    resw 1

; composer scratch
g_pos:          resw 1          ; current write offset into resident_image
g_planptr:      resw 1
g_step:         resw 1
g_imm0:         resw 1
g_curid:        resb 1
                resb 1

%ifdef CFG_PNP
; ISA PnP isolation scratch (cold)
pnp_lfsr:       resb 1          ; running isolation checksum LFSR
pnp_saw:        resb 1          ; a card drove the bus (0x55AA seen)
pnp_next_csn:   resb 1          ; next CSN to hand out
pnp_found_csn:  resb 1          ; CSN of the matched 3Com card
pnp_id:         resb 9          ; isolated serial id: vendor[2] product[2] serial[4] csum[1]
                resb 1          ; pad to even
%endif

;==============================================================================
; STACK -- COLD: the composer/init working stack (reclaimed; the ISR uses isr_stack).
;==============================================================================
segment _STACK stack class=STACK use16
        resb 1024
cold_image_end:                     ; end of the loaded image (DGROUP offset) -- the NC re-test's probe area
                                    ; is placed in the first whole 64 KB block ABOVE this (coh_nc_area)

;==============================================================================
; CODE
;
; _TEXT is in DGROUP (tiny model): CS = DS = ES = SS = DGROUP, one addressable segment, so
; the resident INT 60h handler / ISR (next milestone) can NEAR-call the emitted datapath in
; resident_image. The _BSS + _STACK tail is uninitialized -> minalloc, not stored in the file.
;==============================================================================
group DGROUP _TEXT _DATA _BSS _STACK
segment _TEXT public class=CODE use16

;==============================================================================
; RESIDENT region (kept) -- laid out FIRST so the TSR keeps only up to resident_end and
; reclaims everything after it (the cold composer / probe / init / diagnostics). Holds the
; INT 60h handler, the ISR, the resident state they touch, and the JIT-emitted datapath.
; resb here is stored in the file but stays resident (it must be low/kept).
;==============================================================================
%include "resident.asm"             ; pkt_handler (INT 60h API)
%include "isr.asm"                  ; nic_isr (RX + receiver upcall)

g_nic_io:       resw 1              ; detected I/O base (command reg at +0x0E, windowed cfg at +0x00..)
g_nic_irq:      resw 1              ; detected IRQ
g_w1_base:      resw 1              ; Window-1 data-register base = io_base + gen delta (FIFO/status/free)
g_tx_start:     resw 1              ; precomputed SET_TX_START command (early-start vs store-and-forward)
g_use_dma:      resb 1             ; 1 = bus-master DMA TX active (3C515, >=286): single-transfer on 286, ring on 386+
g_use_large:    resb 1             ; 1 = FDDI-sized large frames active (/j AND 3C515): allowLargePackets
g_rx_len_mask:  resw 1             ; RX length mask: 0x07FF std, 0x1FFF when large (13-bit 3C515 field)
g_copybreak_t:  resw 1             ; RX copybreak threshold (bytes): len<=T -> PIO, len>T -> DMA ring.
                                   ; autotuned at install (copybreak_autotune): T = c_setup / a_PIO.
g_tx_done:      resb 1             ; set by the ISR on TxComplete; awaited by dma_tx_single (286 path)
g_tx_ring:      resb 1             ; 1 = 386+ -> non-blocking COPY ring (movsd) for send_pkt; 0 = 286 -> blocking single-transfer
g_async:        resb 1             ; 1 = zero-copy async TX ring available (AH=0xF1): any bus-master config (>=286)
g_rx_cksum:     resb 1             ; 1 = RX checksum offload on -> sum IP+TCP+payload during the PIO drain (AH=0xF2)
g_rx_cksum_val: resw 1             ; folded native-LE ones-complement sum of the last drained frame
g_rx_is386:     resb 1             ; 1 = 386+ (rx_drain_cksum may use insd); set at install from g_cpu_class,
                                   ; which lives in cold BSS and is freed once the TSR is resident
g_cache_flush_fn: resw 1           ; Phase 2: offset of the selected DMA cache-flush helper (cache.asm). The
                                   ; DMA paths `call word [g_cache_flush_fn]`; the cold coherency self-test
                                   ; (docs/17) picks the tier. Default cache_flush_none (coherent) until then.
g_flush_tier:   resb 1             ; Phase 2: FLUSH_TIER_* verdict from phase_validate_coherency (cold). install
                                   ; maps it -> g_cache_flush_fn. Set NONE at the top of the cold probe so the
                                   ; PIO path (probe skipped) still has a defined value.
g_nc_chipset:   resb 1             ; Phase 2 step 4: /n=<id> opt-in NC chipset (0 = off; NC_CHIP_*). Set by the
                                   ; cold arg scan, read at f_xms_configure (resident) -> must NOT be in cold BSS.
g_nc_effective: resb 1             ; 1 = the cold NC re-test confirmed NC fences the cache -> f_xms_configure marks
                                   ; the ring NC and drops the flush. 0 (default/emulator) -> keep the flush tier.
; (the bus-master TX-DMA structures -- tx_descs / tx_slots -- are placed LAST, past resident_end_pio,
;  so the TSR drops them on the PIO floor; the 286 single-transfer path also drops tx_slots.)
g_mac:          resb 6             ; station address
; receiver handle table: per slot recv_off, recv_seg (0=free), type (0=match all)
htable:         resb MAX_HANDLES * HANDLE_SIZE

; ISR type-demux scratch
rx_len:         resw 1             ; current packet length
cur_handle:     resw 1             ; matched handle (slot offset)
appbuf_off:     resw 1             ; receiver's buffer (upcall-1 result)
appbuf_seg:     resw 1
hdr_buf:        resb 16            ; Ethernet header peek (14 bytes + pad)

; install/uninstall state (resident so the uninstall vendor fn can restore + free)
psp_seg:        resw 1             ; our PSP segment
old_int_off:    resw 1             ; previous INT 60h owner (off,seg for `lds`)
old_int_seg:    resw 1
old_irq_off:    resw 1             ; previous NIC IRQ owner
old_irq_seg:    resw 1
irq_vec:        resb 1             ; computed NIC IRQ vector number
                resb 1

g_off:          resw FRAG__COUNT   ; emitted-fragment offsets (handler/ISR call via these)
g_isr_busy:     resb 1             ; ISR reentrancy guard
isr_work:       resb 1             ; per-interrupt RX work cap counter (MAX_RX_WORK down to 0)
isr_save_ss:    resw 1             ; interrupted task's SS:SP (private-stack switch)
isr_save_sp:    resw 1
isr_stack:      resb 128           ; the ISR's private stack
isr_stack_top:
resident_image: resb 256           ; the composed datapath (tx + rx drain)

; --- statistics (resident; updated by the ISR / send_pkt, read by get_statistics) ---
stat_rx:        dw 0               ; packets received & delivered
stat_tx:        dw 0               ; packets transmitted
stat_rxerr:     dw 0               ; RX errors (card-flagged)
stat_rxdrop:    dw 0               ; RX dropped (no receiver / no buffer)
stat_irq:       dw 0               ; NIC interrupts serviced
stat_txunderrun: dw 0              ; TX underrun/jabber recoveries (early-start tuning)
stat_txwait:    dw 0               ; TX FIFO-room waits that timed out (fast-CPU stall)
stat_adapterfail: dw 0            ; adapter-failure RX-engine resets (ISR self-heal)
pkt_stats:      times 7 dd 0       ; Crynwr get_statistics struct (built on demand)

%ifdef CFG_DEBUG
; --- debug event-log ring (resident; appended by the ISR / handler, dumped by pktdbg) ---
DBG_LOG_SIZE    equ 512
dbg_sig:        db 'PKTDBG00'      ; marker the dump tool can recognise
dbg_log_head:   dw 0               ; ring write index (wraps at DBG_LOG_SIZE)
dbg_log:        times DBG_LOG_SIZE db 0
%endif

; --- end of the always-resident (PIO floor) region. DMA entry points below are reached only
;     when g_use_dma/g_async is active, so a PIO installation can reclaim their code as well.
resident_end_pio:
global resident_end_pio

%include "resident_dma_paths.asm"   ; TX DMA and XMS packet-driver entry points
%include "isr_dma.asm"              ; XMS receive delivery, called by the XMS poll path
%include "resident_dma.asm"         ; DMA-only resident code (VDS locks, teardown) -- dropped on the PIO floor
%include "cache.asm"                ; bus-master DMA cache-coherency flush helper (Phase 2; DMA paths only)
%include "nc.asm"                   ; non-cacheable DMA-region marking (Phase 2 step 4; opt-in /n, real-HW only)

; bus-master TX-DMA structures -- kept ONLY when the DMA path is active (gated on g_use_dma), so
; they sit past resident_end_pio and the PIO floor drops them. RX is always PIO (no RX-DMA buffer/
; descriptor), so only the TX descriptors + ring slots live here. Descriptor layout matches the
; emulator EL3 Down desc (next/status/addr/length). tx_descs[0] doubles as the 286 single-transfer
; down descriptor (the ring is 386+ only); the TX slots below the single boundary exist only for the
; 386+ ring, so the 286 path drops them too.
; Phase 2 (docs/17 Piece 3/4): cache-line (32-byte) align the card-DMA-touched descriptor block so it
; never shares a line with the CPU-hot ring counters below it (TX_RING_N*16 = 64 B = a clean 2 lines,
; so the counters start on a fresh line) -- a future line-granular flush then can't corrupt either.
                alignb 32
tx_descs:       resb TX_RING_N * EL3_DESC_SIZE  ; TX ring descriptors (card DMA-reads them); [0] also serves the 286 single-transfer
                alignb 4
; TX ring counters -- resident on ALL bus-master configs (incl. 286): the zero-copy async ring
; (dma_tx_async) is 8086-clean and needs no per-frame slot copy, so it works on a 286 too. Only the
; ~10 bytes of counters live here; the 6 KB tx_slots stay 386+-only (they back the COPY ring, which a
; 286 can't hide). The ISR also reads tx_ring_count to tell a ring completion from a single-transfer.
tx_ring_head:   resw 1             ; next slot to fill (producer: send_pkt / async_send)
tx_ring_tail:   resw 1             ; oldest in-flight slot (consumer: TxComplete ISR)
tx_ring_count:  resw 1             ; frames currently queued (0..TX_RING_N); 0 => any TxComplete is a single-transfer
tx_dma_busy:    resb 1             ; 1 while a slot's DMA is in flight
                resb 1             ; pad to even
tx_completed:   resw 1             ; ASYNC ext: frames the TxComplete ISR has finished (wraps mod 65536);
                                   ; ASYNC_INFO hands the stack &tx_completed to throttle posts on.

resident_end_single:               ; <== TSR keep boundary for the 286 single-transfer DMA path (descriptors + ring counters)
global resident_end_single

; XMS DMA receive ring state -- present whenever g_use_dma=1 (286 or 386+).
; 286: kept through resident_end_xms_single (drops tx_slots / ring vars).
; 386+: kept through resident_end (includes tx_slots for the TX ring).
xms_dma_armed:  resb 1             ; 0 = PIO / not configured; 1 = XMS ring armed
xms_rx_policy:  resb 1             ; xms_mem_policy_t (VCPI=0, DPMI=1, XMS_COPY=2)
xms_slot_idx:   resb 1             ; current ring slot index (0..xms_nslots-1; cycles mod nslots)
xms_nslots:     resb 1             ; ring depth: 2 (XMS_COPY/286 ping-pong) or RX_RING_N (CONV+386 deep ring)
xms_cfg_off:    resw 1             ; far ptr to caller's xms_rx_cfg_t (offset)
xms_cfg_seg:    resw 1             ; far ptr to caller's xms_rx_cfg_t (segment)
xms_slot_sz:    resw 1             ; bytes per XMS slot
g_rx_irq_masked: resb 1            ; NAPI: 1 = UP_COMPLETE IRQ masked under RX load; the conv-ring drain
                                   ; is deferred to pkt_xms_poll (task) so the ISR can't starve net_poll
                resb 1             ; pad to word alignment
g_intr_enb_full: resw 1           ; full SetIntrEnb mask (incl UP_COMPLETE) saved at configure; the ISR
                                   ; masks UP_COMPLETE out of it, pkt_xms_poll re-arms with the full value
                alignb 32
; RX up-descriptor ring: RX_RING_N entries, cache-line (32-byte) aligned (Phase 2, docs/17 Piece 3:
; the card writes UP_COMPLETE here and the CPU polls it -- a non-coherent cache must invalidate this
; line before the poll, so it must not share a line with neighbouring CPU-written state; RX_RING_N*16 =
; 128 B = a clean 4 lines). CONV uses all N (deeper ring, contiguous slots); XMS_COPY / 286 single-
; transfer use the first 2. desc[i] = xms_rx_descs + i*EL3_DESC_SIZE.
xms_rx_descs:   resb RX_RING_N * EL3_DESC_SIZE
xms_rx_desc0    equ xms_rx_descs                    ; slot-0 alias (the XMS_COPY / 286 2-slot path)
xms_rx_desc1    equ xms_rx_descs + EL3_DESC_SIZE    ; slot-1 alias
xms_gdt:        resb 48            ; INT 15h AH=87h GDT (6 x 8-byte entries; access bytes pre-set)
g_lin_delta:    resd 1             ; Phase 2 4b: CONV/COMMONBUF in-place delivery linear-vs-physical offset =
                                   ; cfg.lin0 - cfg.phys0 (set in f_xms_configure .build_conv). 0 for CONV (real
                                   ; mode, identity-mapped). Under a paging VMM (COMMONBUF/VDS) phys0 is the bus
                                   ; address and lin0 the V86 linear the CPU uses; the ISR recovers each slot's
                                   ; CPU segment as (descriptor.phys + g_lin_delta) >> 4. DMA region: only
                                   ; read with the ring armed, which needs g_use_dma.
; Phase 2 4b descriptor relocation: the conv RX descriptors normally live in the CACHED driver region
; (xms_rx_descs); the card writes UP_COMPLETE there and the CPU polls it, so the per-drain RX flush is
; required. When NC is effective the descriptors are RELOCATED into the (NC-fenced) DMA pool so that flush
; can be DROPPED. These three vars parameterise the descriptor block's location so one code path serves
; both: g_desc_far = CPU far ptr (seg:off), g_desc_phys = the card-facing physical base, g_rx_flush_fn =
; the RX-side flush helper (separate from the TX g_cache_flush_fn so only the RX flush drops). Defaults
; (set at configure) reproduce the cached path exactly: CS:xms_rx_descs + the selected flush tier. They live
; in the DMA region (past resident_end_pio): every reader is behind the pkt_do_xms g_use_dma gate.
g_desc_far:     resd 1             ; descriptor block far ptr (offset, then segment) -- CPU access (ISR/build/poll)
g_desc_phys:    resd 1             ; descriptor block physical base -- card UP_LIST/NEXT
g_rx_flush_fn:  resw 1             ; RX-drain cache helper (= g_cache_flush_fn, or cache_flush_none when NC-relocated)
g_v86:          resb 1             ; 1 = running under a paging V86 host (SMSW PE=1) -> seg<<4 is not the bus
                                   ; address; set by dma_v86_forbid_check (DMA region: DMA paths read it)
g_vds_span_held: resb 1            ; 1 = tx_span_dds holds the VDS lock on [tx_descs, resident_end) (V86)
g_nc_marked:    resb 1             ; 1 = f_xms_configure fenced the live ring's 64 KB block NC (release restores)
xms_cfg_ver:    resb 1             ; the configured cfg.version (1 = legacy pool: never relocate / mark NC)
xms_inplace:    resb 1             ; xms_rx_deliver scratch: 1 = the receiver took this slot in place
xms_nheld:      resb 1             ; slots currently held in place by the receiver (released at the next poll)
xms_held:       resb RX_RING_N     ; per slot: 1 = held in place (STATUS left complete until released)
nc_saved_ok:    resb 1             ; 1 = nc_saved_base/size hold the chipset's pre-mark region-0 registers
nc_saved_base:  resb 1
nc_saved_size:  resb 1
g_tx_slot_sz:   resw 1             ; TX ring slot size: TX_SLOT_SZ, or TX_SLOT_LARGE with /j (build_plan)
tx_vds_held:    resb TX_RING_N     ; per TX slot: 1 = tx_vds_dds[i] still holds an AH=F1 frame's VDS lock
                alignb 2
tx_span_dds:    resb DDS_LEN       ; VDS DDS: the driver's own DMA span, locked for the driver's lifetime
tx_vds_dds:     resb TX_RING_N * DDS_LEN   ; VDS DDS per TX slot (AH=F1 per-send locks under V86)

resident_end_xms_single:          ; <== TSR keep boundary: 286 DMA + XMS (drops TX ring slots)
global resident_end_xms_single

                alignb 32                       ; Phase 2 (docs/17 Piece 4): cache-line align the DMA TX slots
                                                ; (card reads them; both slot sizes are multiples of 32, so
                                                ; every slot stays line-aligned) -- 386+-only, past the 286 boundary
tx_slots:       resb TX_RING_N * TX_SLOT_LARGE  ; 386+ COPY-ring frame slots (dma_tx_enqueue movsd's the frame in).
                                                ; Reserved for /j; install keeps TX_RING_N * g_tx_slot_sz of it

resident_end:                      ; <== end of the image's resident reservation (the 386+ ring keeps up to
                                   ;     tx_slots + TX_RING_N * g_tx_slot_sz: see install)
global resident_end

;==============================================================================
; COLD region (reclaimed after install) -- entry, detection, compose, install, diagnostics.
;==============================================================================
..start:
        mov     bp, es              ; ES = PSP at .EXE entry -- save for the TSR keep
        mov     ax, DGROUP
        mov     ds, ax
        mov     es, ax              ; composer uses ES:DI for the emit destination
        ; Clear the cold parse/detect flags. They live in _BSS, which DOS does NOT zero on
        ; .EXE load: a fresh boot happens to hand us zeroed memory, but a RELOAD (3cpd /u
        ; then 3cpd again) lands in dirty freed memory -- a stale g_force8 there forces the
        ; 8088 8-bit datapath (wrong on a 16-bit 3C515) and disables DMA. (ES = DGROUP here.)
        cld
        mov     di, g_cpu_class
        mov     cx, 10              ; g_cpu_class, g_nic_gen, g_manual, g_force8, g_force286, g_want_dma,
                                    ; g_want_large, g_want_v86trust, g_wbinvd_ok, g_coh_nosafe (a stale /j or
                                    ; /v must not survive a reload either)
        xor     al, al
        rep     stosb
        ; The NC opt-in state is RESIDENT (read at configure) but set during this cold arg scan, so it can't
        ; ride the cold-BSS clear above. Zero it here so /n unset => off, and a reload starts clean.
        mov     byte [g_nc_chipset], 0
        mov     byte [g_nc_effective], 0
        mov     byte [g_nc_marked], 0       ; (DMA-region NC bookkeeping; resb is not load-zeroed)
        mov     byte [nc_saved_ok], 0
        mov     [psp_seg], bp

        ; --- command tail scan ---
        ;   /u        uninstall the resident driver and exit
        ;   /b=NNN    manual I/O base (hex) -> skip the ID-port probe, attach at NNN
        ;   /q=NN     manual IRQ (decimal)  -> used with /b=
        ; Manual config lets the driver bind to a card at a known base (PnP-only cards, odd
        ; setups, or an emulator) without the ID-port contention.
        mov     es, bp              ; ES = PSP for the tail scan
        mov     al, [es:0x80]       ; command-tail length
        xor     ah, ah
        add     ax, 0x81            ; AX = end offset
        mov     [tail_end], ax
        mov     si, 0x81
.scan_tail:
        cmp     si, [tail_end]
        jae     .args_done
        cmp     byte [es:si], '/'
        jne     .st_next
        mov     al, [es:si + 1]
        or      al, 0x20            ; tolower
        cmp     al, 'u'
        je      do_uninstall
        cmp     al, 'b'
        je      .opt_base
        cmp     al, 'q'
        je      .opt_irq
        cmp     al, '8'
        jne     .chk_286
        mov     byte [g_force8], 1  ; force 8-bit byte-loop datapath (test the 8088 fragment)
        jmp     .st_next
.chk_286:
        cmp     al, '2'
        jne     .chk_dma
        mov     byte [g_force286], 1 ; force 286-class datapath (test 286 16-bit PIO + single-transfer DMA)
        jmp     .st_next
.chk_dma:
        cmp     al, 'd'
        jne     .chk_large
        mov     byte [g_want_dma], 1 ; /d -> request bus-master TX DMA (gated to 3C515 + >=286)
        jmp     .st_next
.chk_large:
        cmp     al, 'j'
        jne     .chk_nc
        mov     byte [g_want_large], 1 ; /j -> request FDDI-sized large frames (gated to 3C515)
        jmp     .st_next
.chk_nc:
        cmp     al, 'n'
        je      .opt_nc             ; /n=<id> -> opt in to a non-cacheable DMA region on a known chipset
        cmp     al, 'v'
        jne     .chk_gen
        mov     byte [g_want_v86trust], 1 ; /v -> trust the V86 host's WBINVD emulation (JEMM386 does)
        jmp     .st_next
.chk_gen:
        cmp     al, '5'
        jne     .st_next
        mov     byte [g_nic_gen], 1 ; /5 -> Corkscrew (3C515): EEPROM +0x2000, W1 base +0x10
.st_next:
        inc     si
        jmp     .scan_tail
.opt_base:
        add     si, 3               ; skip "/b="
        call    parse_hex16         ; ES:SI -> hex -> BX, SI advanced
        mov     [g_nic_io], bx
        mov     byte [g_manual], 1
        jmp     .scan_tail
.opt_irq:
        add     si, 3               ; skip "/q="
        call    parse_dec16         ; ES:SI -> decimal -> BX, SI advanced
        mov     [g_nic_irq], bx
        jmp     .scan_tail
.opt_nc:
        ; /n=<id> -- opt in to a non-cacheable DMA region on a KNOWN chipset (default off). Explicit id (not
        ; a probe) so an unrecognized board never gets speculative 0x22 writes: 1=OPTi 2=Eteq 3=UMC 4=SiS
        ; 254=synthetic structural test. Still re-test-gated before any flush is dropped (nc.asm safety model).
        add     si, 3               ; skip "/n="
        call    parse_dec16         ; ES:SI -> decimal -> BX
        mov     [g_nc_chipset], bl
        jmp     .scan_tail
.args_done:
        mov     ax, DGROUP
        mov     es, ax              ; restore ES = DGROUP for the composer

        mov     dx, msg_banner
        call    print_str
%ifdef CFG_DEBUG
        mov     dx, msg_dbgon
        call    print_str
%endif

        call    detect_cpu          ; -> g_cpu_class
        cmp     byte [g_force8], 0  ; /8 -> force the 8088-class datapath (test 8-bit PIO on a fast CPU)
        je      .chk_force286
        mov     byte [g_cpu_class], CPU_8088
        jmp     .cpu_ok
.chk_force286:
        cmp     byte [g_force286], 0 ; /2 -> force the 286-class datapath (16-bit PIO + single-transfer DMA)
        je      .cpu_ok
        mov     byte [g_cpu_class], CPU_80286
.cpu_ok:
        mov     dx, msg_cpu
        call    print_str
        mov     al, [g_cpu_class]
        add     al, '0'
        call    print_char          ; CPU class digit (0=8088,1=286,2=386)

        ; --- 5150 short-circuit -------------------------------------------------
        ; On an 8088/8086 the capability axis collapses to PIO: no protected mode, no
        ; bus-master, no VMM. The >=286-only cold work (bus-master DMA validation and its
        ; VDS/cache machinery) is deferred to the Corkscrew generation, so today both paths
        ; fall straight through to the floor PIO compose. The split is kept as the documented
        ; hook for that >=286 work.
        cmp     byte [g_cpu_class], CPU_8088
        jbe     .floor
        ; (>=286) bus-master DMA validation moved below -- it needs the activated card + build_plan
.floor:
        ; ISA NIC detection. The native 3Com ID-port sequence is the universal EtherLink III
        ; ISA mechanism and runs on ANY CPU -- it's just port I/O. ISA PnP is a SEPARATE
        ; software protocol over fixed ports (0x279/0xA79 + relocatable read) that ALSO works
        ; on any ISA bus: it is NOT CPU-dependent (no PnP BIOS or 286+ needed to run the
        ; isolation -- a software PnP manager does it). PnP only matters for a 3C509B left in
        ; PnP-only mode or already claimed by a PnP BIOS, so it is a FULL-PROFILE add
        ; (CFG_PNP), compiled out of the minimal floor for size -- gated by profile, not CPU.
%ifdef CFG_FAKENIC
        ; test build (no emulator has a 3C509): skip the probe, inject a fake NIC so the
        ; full el3_init -> compose -> install path runs and the resident driver is testable.
        mov     word [g_nic_io], 0x300
        mov     word [g_nic_irq], 0x000A
        mov     si, fake_mac
        mov     di, g_mac
        mov     cx, 6
        rep     movsb
        clc
%else
        ; manual config (/b= given): skip the ID-port probe, attach at the specified base.
        cmp     byte [g_manual], 1
        jne     .auto_detect
        cmp     word [g_nic_irq], 0
        jne     .have_irq
        mov     word [g_nic_irq], 0x000A    ; default IRQ 10 if /q= omitted
.have_irq:
        call    el3_load_mac_io             ; read MAC via Window-0 EEPROM at the given base
        clc
        jmp     .nic_found
.auto_detect:
%ifdef CFG_PNP
        ; >=286 (16-bit ISA): try ISA PnP first -- it finds a 3C515 AND a PnP-mode 3C509B --
        ; then fall back to the legacy ID-port. On an 8088 a 3C515 can't exist (16-bit card)
        ; so we go straight to the legacy probe and skip the PnP subsystem entirely.
        cmp     byte [g_cpu_class], CPU_8088
        jbe     .legacy_only
        call    detect_nic_pnp      ; direct ISA PnP isolation -> g_nic_io/irq/mac
        jnc     .nic_found
.legacy_only:
        call    detect_nic          ; legacy 3Com ID-port (Tomahawk)
%else
        call    detect_nic          ; floor: native 3Com ID-port (Tomahawk) only
%endif
%endif
        jc      .nic_none           ; no card found
.nic_found:
        mov     dx, msg_nic         ; "3C509 I/O=0x"
        call    print_str
        mov     ax, [g_nic_io]
        call    print_hex16
        mov     dx, msg_irq         ; " IRQ=0x"
        call    print_str
        mov     ax, [g_nic_irq]
        call    print_hex16
        call    print_mac           ; " MAC=xx:xx:.."
        mov     dx, msg_crlf
        call    print_str

        call    validate_mac        ; reject an implausible station address before building on it --
        jc      .bad_mac            ; all-FF (off-device read, e.g. wrong /5 gen for a 3c509) / all-00 / multicast

        call    build_plan          ; per-gen Window-1 base + TX-start cmd + PIO immediates
        call    el3_init            ; bring the activated card to operational state (uses g_tx_start)
        call    phase_validate_dma  ; (>=286) test-before-trust: prove bus-master DMA or fall back to PIO

        ; Phase 2: RX cache-coherency self-test (MAC internal loopback) -> g_flush_tier. On QEMU (no
        ; cache modelled) this concludes coherent -> NONE; on a non-coherent 486+ it picks WBINVD.
        call    phase_validate_coherency
        call    vds_cold_release    ; V86: drop the cold probe span's VDS lock (+ the span lock if now PIO)
        mov     dx, msg_coh
        call    print_str
        mov     dx, msg_coh_nosafe
        cmp     byte [g_coh_nosafe], 0
        jne     .coh_report
        mov     dx, msg_coh_none
        cmp     byte [g_flush_tier], FLUSH_TIER_NONE
        je      .coh_report
        mov     dx, msg_coh_wbinvd
.coh_report:
        call    print_str
        ; NC status (only when /n=<id> opted in): validated by the cold re-test, or requested-but-ineffective
        cmp     byte [g_nc_chipset], NC_CHIP_NONE
        je      .nc_noreport
        mov     dx, msg_nc_off
        cmp     byte [g_nc_effective], 0
        je      .nc_report
        mov     dx, msg_nc_eff
.nc_report:
        call    print_str
.nc_noreport:
        ; report the resolved DMA decision -- AFTER the coherency phase, which can still drop to PIO
        mov     dx, msg_dma
        call    print_str
        mov     dx, msg_dma_on
        cmp     byte [g_use_dma], 0
        jne     .dma_report
        mov     dx, msg_dma_pio_nc
        cmp     byte [g_coh_nosafe], 0
        jne     .dma_report
        mov     dx, msg_dma_pio
.dma_report:
        call    print_str

        call    copybreak_autotune  ; RX copybreak threshold T = c_setup / a_PIO (cost model + PIT-timed probe)
        mov     dx, msg_cb
        call    print_str
        mov     ax, [g_copybreak_t]
        call    print_hex16
        mov     dx, msg_crlf
        call    print_str

        call    compose_resident    ; ax = emitted length, fills resident_image + g_off
        or      ax, ax
        jz      .fail
        mov     [g_emitted_len], ax
%ifdef CFG_DEBUG
        mov     dx, msg_emit
        call    print_str
        mov     ax, [g_emitted_len]
        call    print_hex16
%endif

        call    copy_down           ; ax = paragraphs to keep
        mov     [g_keep_para], ax

        call    install             ; hook INT 60h, free env, DOS TSR-keep (never returns)
        ; (NIC IRQ hook + ISR receiver upcall land with real 3c509 hardware)
.nic_none:
        mov     dx, msg_no_nic
        call    print_str
.fail:
        mov     ax, 0x4C01
        int     0x21
.bad_mac:
        mov     dx, msg_badmac
        call    print_str
        jmp     .fail

;------------------------------------------------------------------------------
; do_uninstall -- `3cpd /u`: find the resident driver via the INT 60h vector + the
; "PKT DRVR" signature, ask it to tear down (vendor fn 0x82 restores vectors + masks the
; IRQ and returns its PSP in BX), then free its memory block. Separate process from the
; resident instance, so freeing the resident block is safe.
;------------------------------------------------------------------------------
do_uninstall:
        mov     ax, DGROUP
        mov     ds, ax
        mov     ax, 0x3500 | PKTINT     ; get INT 60h vector -> ES:BX
        int     0x21
        ; verify "PKT DRVR" at ES:BX+3 before trusting the vector
        mov     di, bx
        add     di, 3
        mov     si, sig_pktdrvr
        mov     cx, 8
.sigcmp:
        mov     al, [si]
        cmp     al, [es:di]
        jne     .notinst
        inc     si
        inc     di
        loop    .sigcmp
        ; it's ours -- tear down, then free the resident block
        mov     ah, 0x82                ; PD_UNINSTALL -> BX = resident PSP
        int     PKTINT
        mov     es, bx
        mov     ah, 0x49                ; free the resident memory block
        int     0x21
        mov     dx, msg_uninst
        call    print_str
        mov     ax, 0x4C00
        int     0x21
.notinst:
        mov     dx, msg_notinst
        call    print_str
        mov     ax, 0x4C01
        int     0x21

;------------------------------------------------------------------------------
; detect_cpu -- full non-CPUID class ladder: 8088 / 286 / 386 / 486 / CPUID-capable.
; Sets g_cpu_class. The 8086/286 split is the 16-bit FLAGS bits 12-15 test (8088-safe);
; the 386/486/CPUID split uses the 32-bit EFLAGS AC and ID flags (only reached on 386+, so
; the floor never executes a 32-bit instruction). Finer family/feature detail needs the
; CPUID-parsing layer (lifted when the cache-coherency tier lands). ~122 bytes, cold.
;------------------------------------------------------------------------------
detect_cpu:
        pushf
        pop     ax
        mov     cx, ax              ; save original FLAGS
        and     ax, 0x0FFF          ; try to clear bits 12-15
        push    ax
        popf
        pushf
        pop     ax
        and     ax, 0xF000
        cmp     ax, 0xF000          ; stuck set -> 8086/8088
        je      .is8088
        or      cx, 0xF000          ; try to set bits 12-15
        push    cx
        popf
        pushf
        pop     ax
        and     ax, 0xF000
        jz      .is286              ; stuck clear (can't set in real mode) -> 286
        ; --- 386+ : 32-bit EFLAGS tests (unreachable on 8086/286) ---
        cpu 386
        pushfd
        pop     eax
        mov     ecx, eax
        xor     eax, 0x00040000     ; toggle AC (bit 18): 386 can't, 486+ can
        push    eax
        popfd
        pushfd
        pop     eax
        xor     eax, ecx
        test    eax, 0x00040000
        jz      .is386
        mov     eax, ecx
        xor     eax, 0x00200000     ; toggle ID (bit 21): no-CPUID can't, CPUID can
        push    eax
        popfd
        pushfd
        pop     eax
        xor     eax, ecx
        test    eax, 0x00200000
        jz      .is486
        mov     byte [g_cpu_class], CPU_CPUID
        ret
.is486:
        mov     byte [g_cpu_class], CPU_80486
        ret
.is386:
        mov     byte [g_cpu_class], CPU_80386
        ret
.is286:
        mov     byte [g_cpu_class], CPU_80286
        ret
.is8088:
        mov     byte [g_cpu_class], CPU_8088
        ret
        cpu 8086                    ; restore floor-safety check for the rest of the file

;------------------------------------------------------------------------------
; phase_validate_dma (>=286 cold phase, AFTER el3_init) -- test-before-trust (docs/04). build_plan
; tentatively set g_use_dma (3C515 + /d + >=286); here we PROVE the bus-master engine actually works
; before compose emits the DMA datapath: DMA a probe descriptor and confirm the card writes
; DN_COMPLETE back into it. Cold phase -> no ISR, so poll the descriptor STATUS, bounded by BIOS
; ticks. Pass -> keep g_use_dma. Fail (no DN_COMPLETE in time = wedged/absent engine) -> clear it,
; so compose falls back to the proven PIO floor. Mirrors dma_tx_single's descriptor + kick.
; Clobbers AX,BX,CX,DX (ES preserved). DS = DGROUP throughout.
;------------------------------------------------------------------------------
BM_TEST_LEN     equ 60                      ; probe frame size (min Ethernet payload)
phase_validate_dma:
        cmp     byte [g_use_dma], 0
        je      .pv_done                    ; PIO path: no bus-master engine to test

        push    es
        ; (cs << 4) -> dx:ax ; both descriptor and probe buffer live in CS=DGROUP (<1 MB)
        mov     bx, cs
        mov     ax, bx
        mov     cl, 4
        shl     ax, cl
        mov     dx, bx
        mov     cl, 12
        shr     dx, cl
        mov     cx, ax                      ; bx:cx = (cs << 4)
        mov     bx, dx
        ; descriptor[0].ADDR = phys(bm_test_buf); NEXT=0, STATUS=0, LEN=BM_TEST_LEN
        add     ax, bm_test_buf
        adc     dx, 0
        mov     [tx_descs + EL3_DESC_ADDR], ax
        mov     [tx_descs + EL3_DESC_ADDR + 2], dx
        xor     ax, ax
        mov     [tx_descs + EL3_DESC_NEXT], ax
        mov     [tx_descs + EL3_DESC_NEXT + 2], ax
        mov     [tx_descs + EL3_DESC_STATUS], ax
        mov     [tx_descs + EL3_DESC_STATUS + 2], ax
        mov     [tx_descs + EL3_DESC_LEN + 2], ax
        mov     word [tx_descs + EL3_DESC_LEN], BM_TEST_LEN
        ; Non-snooping write-back cache: the descriptor we just built may still be dirty in the cache, so the
        ; card would fetch stale bytes. Write it back first (only where WBINVD is safe: 486+, real mode or /v).
        cmp     byte [g_wbinvd_ok], 0
        je      .pv_noflush
        db      0x0F, 0x09                  ; WBINVD
.pv_noflush:
        ; DownListPtr <- phys(tx_descs) (two 16-bit OUTs)
        mov     ax, cx
        mov     dx, bx
        add     ax, tx_descs
        adc     dx, 0
        push    dx
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_DOWN_LIST_PTR
        out     dx, ax
        pop     ax
        add     dx, 2
        out     dx, ax
        ; kick StartDmaDown
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_START_DMA_DOWN
        out     dx, ax
        ; poll DN_COMPLETE in the descriptor, bounded by elapsed BIOS ticks
        xor     ax, ax
        mov     es, ax                      ; ES = BIOS data area
        mov     bx, [es:BIOS_TICK_COUNT]    ; start tick
        mov     cx, bx                      ; last tick seen
.pv_wait:
        test    word [tx_descs + EL3_DESC_STATUS], EL3_DESC_DN_COMPLETE
        jnz     .pv_pass
        mov     ax, [es:BIOS_TICK_COUNT]
        ; The first poll may have cached the descriptor line before the card wrote DN_COMPLETE; on a
        ; non-snooping cache every later poll would hit that stale line and time out -> a false PIO verdict
        ; before the coherency probe ever runs. Invalidate once per BIOS tick so the poll re-reads memory.
        cmp     ax, cx
        je      .pv_same_tick
        mov     cx, ax
        cmp     byte [g_wbinvd_ok], 0
        je      .pv_same_tick
        db      0x0F, 0x09                  ; WBINVD
.pv_same_tick:
        sub     ax, bx
        cmp     ax, EL3_DMA_TX_TICKS
        jb      .pv_wait
        ; timeout: bus-master unproven -> fall back to the PIO floor
        call    dma_force_pio
.pv_pass:
        pop     es
.pv_done:
        ret

; bm_test_buf -- the probe frame the bus-master DMA test downloads. dest = broadcast so if it does
; reach the wire it's a well-formed broadcast, not garbage; the rest is don't-care (the test only
; proves the card DMA-read it). Cold (reclaimed after install).
bm_test_buf:    db 0xFF,0xFF,0xFF,0xFF,0xFF,0xFF
                times (BM_TEST_LEN - 6) db 0x00

;------------------------------------------------------------------------------
; phase_validate_coherency (>=286 DMA cold phase, AFTER phase_validate_dma) -- Phase 2 RX cache-
; coherency self-test (docs/17). With the bus-master engine proven, decide whether the CPU sees the
; card's RX-DMA writes WITHOUT a cache flush. Mechanism (the RX failure mode that matters most):
;   - warm a dest buffer with pattern A (the "stale" marker), in the instruction just before the DMA
;   - enable MAC internal loopback (Window 4 NET_DIAG bit 5): a bus-master TX is received back into the
;     armed RX up-descriptor instead of reaching the wire
;   - TX a frame carrying pattern B (B != A) -> the card RX-DMAs B into the dest buffer
;   - poll UP_COMPLETE, then read the dest with NO flush: == B -> COHERENT (tier NONE);
;     == A -> the CPU read a stale cached line -> NON-COHERENT (WBINVD on 486+, SW-evict on 386)
; Three trials; any stale OR a timeout -> non-coherent (conservative -- can't prove coherent, don't assume
; it). On QEMU/TCG (no cache modelled) the loopback delivers B and every trial reads fresh -> NONE: this
; is the structural verification (probe runs end-to-end, concludes coherent, no flush, no regression). The
; verdict lands in g_flush_tier; install maps it to the resident cache_flush helper. Cold; clobbers
; AX,BX,CX,DX,SI and ES (ES restored). DS = DGROUP. Leaves the card in Window 1 (el3_init's operating win).
;------------------------------------------------------------------------------
COH_BUF_LEN     equ 128                     ; RX dest capacity (small -> fits any cache; copybreak is 0 here)
COH_FRAME_LEN   equ 64                      ; loopback frame length (min Ethernet payload)
COH_TRIALS      equ 3
COH_PAT_A       equ 0xA5A5                  ; "stale" marker pre-warmed into the dest (both words)
COH_PAT_B       equ 0x5B5B                  ; "fresh" marker the card DMA-writes via loopback (both words)
COH_PAT_OFF     equ 16                      ; patterns live at frame byte 16 (past the Ethernet header): the
                                            ; probe frame is a well-formed BROADCAST, so a real MAC's RX address
                                            ; filter passes it in loopback (a pattern-derived multicast DA may not)
phase_validate_coherency:
        mov     byte [g_flush_tier], FLUSH_TIER_NONE    ; coherent default (also the PIO answer)
        cmp     byte [g_use_dma], 0
        je      .pvc_done                               ; PIO floor: no bus-master path to protect

        push    es
        ; --- enable internal MAC loopback: Window 4, NET_DIAG |= INTERNAL_LB ---
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_SELECT_WINDOW | EL3_W4_MEDIA
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_W4_NET_DIAG
        in      ax, dx
        or      ax, EL3_NET_DIAG_INTERNAL_LB
        out     dx, ax
        ; make Up/DnComplete visible in IntStatus: the trials poll completion there (an I/O port is never
        ; cached) rather than in the in-memory descriptor, whose line a non-snooping cache would pin stale
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_SET_STATUS_ENB | 0x07FF
        out     dx, ax

%ifdef CFG_FORCE_NC
        jmp     .pvc_noncoherent                        ; structural test (no cache to read stale): force the
                                                        ; non-coherent path so the opt-in NC re-test runs
%endif
        ; base verdict: COH_TRIALS loopback trials into coh_rx_buf; any stale OR timeout -> non-coherent
        mov     byte [coh_trials_left], COH_TRIALS
.pvc_loop:
        mov     di, coh_rx_buf
        call    coh_one_trial
        jc      .pvc_noncoherent
        dec     byte [coh_trials_left]
        jnz     .pvc_loop
        jmp     .pvc_cleanup                            ; all fresh -> coherent -> g_flush_tier stays NONE

.pvc_noncoherent:
        ; Non-coherent: DMA is only safe with a flush we may actually execute. WBINVD needs a 486+ AND (real
        ; mode OR /v -- under V86 it is a privileged #GP the host must emulate). Without it (<486: the 386
        ; software-evict tier is deferred, docs/17; V86 without /v) there is NO safe flush -> drop to the PIO
        ; floor rather than DMA with stale lines. On QEMU this branch is unreachable without CFG_FORCE_NC.
        cmp     byte [g_wbinvd_ok], 0
        jne     .pvc_flush_ok
        call    dma_force_pio
        mov     byte [g_coh_nosafe], 1                  ; report: PIO because non-coherent w/o a safe flush
        jmp     .pvc_cleanup                            ; tier stays NONE (PIO has no DMA to flush)
.pvc_flush_ok:
        mov     byte [g_flush_tier], FLUSH_TIER_WBINVD  ; the always-correct fallback if NC is unavailable
.pvc_nc:
        ; --- Phase 2 step 4 (opt-in /n=<id>): try to fence a region non-cacheable and RE-TEST (coh_nc_trial,
        ; COH_TRIALS times, both directions). Fresh after marking -> NC genuinely fences the cache -> arm
        ; g_nc_effective; f_xms_configure then marks the LIVE ring's block NC and drops the flush. The flush
        ; stays armed here -- it is dropped only at configure, only after the ring is actually marked. ---
        cmp     byte [g_nc_chipset], NC_CHIP_NONE
        je      .pvc_cleanup
        ; --- Phase 2 step 4b GATE: chipset NC fences only help WRITE-BACK caches. The base test above flags
        ; non-coherence from the RX-READ direction (card writes, CPU reads stale), which fires identically on
        ; write-through AND write-back -- but on a write-through cache the CPU's writes reach memory at once
        ; (the card reads them fresh) so chipset NC is the WRONG tool; invalidation already suffices there.
        ; Probe the CPU-WRITE->card-READ direction to tell WB from WT. (Reached only with g_wbinvd_ok, so the
        ; probe's WBINVD and the chipset port writes never run under V86 without /v.) ---
        call    coh_is_writeback                        ; CF=1 -> write-back (NC-eligible); CF=0 -> write-through
%ifdef CFG_FORCE_NC
        stc                                             ; structural test: the cacheless emulator probes as
                                                        ; write-through, so force the WB verdict to keep the
                                                        ; NC mark + re-test path exercised under CFG_FORCE_NC
%endif
        jnc     .pvc_cleanup                            ; write-through / no cache -> NC not the tool -> keep flush
        ; RE-TEST in the SAME shape configure will use: one naturally aligned 64 KB block (nc_span64), with
        ; the probe at the END of a NON-ZERO block so a wrong base unit (a 16 KB-vs-64 KB error leaves base 0
        ; unaffected) or a too-small size code misses the probe and FAILS the re-test. Needs owned memory above
        ; the image (coh_nc_area); none -> no NC.
        call    coh_nc_area                             ; -> nc_area_seg/phys; CF=1 -> no usable area
        jc      .pvc_cleanup
        mov     ax, [nc_area_phys]
        mov     dx, [nc_area_phys + 2]
        mov     cx, NCA_LEN
        call    nc_span64                               ; BX = base_kb of the area's 64 KB block
        jc      .pvc_nc_unlock
        call    nc_mark_region                          ; fence it NC (CF=1 -> unknown chipset)
        jc      .pvc_nc_unlock
        mov     byte [coh_trials_left], COH_TRIALS
.pvc_nc_trial:
        call    coh_nc_trial                            ; both directions fresh with no flush?
        jc      .pvc_nc_clear
        dec     byte [coh_trials_left]
        jnz     .pvc_nc_trial
        mov     byte [g_nc_effective], 1                ; NC fences the cache -> configure may mark the ring
.pvc_nc_clear:
        call    nc_clear_region                         ; undo the transient probe marking, pass or fail
.pvc_nc_unlock:
        call    coh_nc_area_release

.pvc_cleanup:
        ; stop the probe's DMA first: a timed-out trial leaves coh_up_desc armed, and the probe buffers are
        ; cold memory install reclaims (the PIO fallback above already quiesced; again is harmless)
        call    dma_quiesce
        ; clear loopback (Window 4 NET_DIAG &= ~INTERNAL_LB), then restore Window 1 (operating)
        mov     dx, [g_nic_io]
        add     dx, EL3_W4_NET_DIAG
        in      ax, dx
        and     ax, (~EL3_NET_DIAG_INTERNAL_LB) & 0xFFFF
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_SELECT_WINDOW | EL3_W1_OPERATING
        out     dx, ax
        pop     es
.pvc_done:
        ret

;------------------------------------------------------------------------------
; coh_nc_area -- place the NC re-test probe area: NCA_LEN bytes at the TOP of the first whole 64 KB block
; above the loaded image (non-zero block, probe at its end -> a wrong NC base unit or size code misses it).
; The memory must be ours: below PSP:[2] (a .EXE owns up to there). Under V86 (/v; the NC path is only
; reached with a safe flush) it must also VDS-prove identity (lock held until coh_nc_area_release).
; out: CF=0 -> nc_area_seg (offset 0) + nc_area_phys; CF=1 -> no usable area. Cold; clobbers AX,BX,CX,DX,ES.
;------------------------------------------------------------------------------
NCA_LEN         equ 512                         ; probe area: up-descriptor +0, src frame +64, dst +256
NCA_UPD         equ 0
NCA_SRC         equ 64
NCA_DST         equ 256
coh_nc_area:
        push    si
        push    di
        mov     si, cold_image_end
        call    cs_phys                                 ; dx:ax = phys(image end)
        add     ax, 0xFFFF
        adc     dx, 0                                   ; DX = first whole 64 KB block above the image
        mov     bx, dx
        inc     dx
        mov     cl, 12
        shl     dx, cl                                  ; DX = segment just past that block
        mov     es, [psp_seg]
        cmp     dx, [es:0x02]                           ; PSP:[2] = first segment beyond our allocation
        ja      .cna_fail
        mov     cl, 12
        shl     bx, cl
        add     bx, (0x10000 - NCA_LEN) >> 4            ; BX = probe area segment (top NCA_LEN of the block)
        mov     [nc_area_seg], bx
        mov     ax, bx
        mov     dx, bx
        mov     cl, 4
        shl     ax, cl
        mov     cl, 12
        shr     dx, cl
        mov     [nc_area_phys], ax
        mov     [nc_area_phys + 2], dx
        cmp     byte [g_v86], 0
        je      .cna_ok
        mov     di, nc_area_dds                         ; V86 (/v): the area must be identity-mapped too
        xor     si, si
        mov     cx, NCA_LEN
        call    vds_lock_prove                          ; BX = segment
        jc      .cna_fail
.cna_ok:
        pop     di
        pop     si
        clc
        ret
.cna_fail:
        pop     di
        pop     si
        stc
        ret

; coh_nc_area_release -- drop the probe area's VDS lock (V86 only). Cold; clobbers AX, DX, DI.
coh_nc_area_release:
        cmp     byte [g_v86], 0
        je      .cnr_done
        push    es
        mov     di, nc_area_dds
        call    vds_unlock_di
        pop     es
.cnr_done:
        ret

;------------------------------------------------------------------------------
; coh_nc_trial -- one NC re-test trial in the probe area (loopback enabled, the area's block marked NC).
; Proves BOTH directions without a flush: seed dst=A and src=OLD, build the descriptors (up-descriptor in the
; area, down = tx_descs -> src), WBINVD (pushes out everything cached before the mark -- marking evicts
; nothing), then READ dst, src and the up-descriptor STATUS: that allocates their lines iff the area is STILL
; cacheable. Write src=NEW, loopback it, wait via IntStatus. Pass only if dst == NEW (the card saw the CPU's
; write AND the CPU sees the card's) and the descriptor STATUS reads UP_COMPLETE. Stale A -> RX direction
; cached; OLD -> TX direction cached. Only reached with g_wbinvd_ok. CF=0 pass. Cold; clobbers AX,BX,CX,DX,ES.
;------------------------------------------------------------------------------
coh_nc_trial:
        mov     es, [nc_area_seg]
        mov     word [es:NCA_DST + COH_PAT_OFF],     COH_PAT_A
        mov     word [es:NCA_DST + COH_PAT_OFF + 2], COH_PAT_A
        mov     word [es:NCA_SRC],     0xFFFF           ; broadcast DA
        mov     word [es:NCA_SRC + 2], 0xFFFF
        mov     word [es:NCA_SRC + 4], 0xFFFF
        mov     word [es:NCA_SRC + COH_PAT_OFF],     WB_PAT_OLD
        mov     word [es:NCA_SRC + COH_PAT_OFF + 2], WB_PAT_OLD
        ; up-descriptor (in the area): ADDR = phys(dst), NEXT = 0, STATUS = 0, LEN = COH_BUF_LEN
        mov     ax, [nc_area_phys]
        mov     dx, [nc_area_phys + 2]
        add     ax, NCA_DST
        adc     dx, 0
        mov     [es:NCA_UPD + EL3_DESC_ADDR], ax
        mov     [es:NCA_UPD + EL3_DESC_ADDR + 2], dx
        xor     ax, ax
        mov     [es:NCA_UPD + EL3_DESC_NEXT], ax
        mov     [es:NCA_UPD + EL3_DESC_NEXT + 2], ax
        mov     [es:NCA_UPD + EL3_DESC_STATUS], ax
        mov     [es:NCA_UPD + EL3_DESC_STATUS + 2], ax
        mov     word [es:NCA_UPD + EL3_DESC_LEN], COH_BUF_LEN
        mov     [es:NCA_UPD + EL3_DESC_LEN + 2], ax
        ; down-descriptor (tx_descs): ADDR = phys(src), LEN = COH_FRAME_LEN
        mov     ax, [nc_area_phys]
        mov     dx, [nc_area_phys + 2]
        add     ax, NCA_SRC
        adc     dx, 0
        mov     [tx_descs + EL3_DESC_ADDR], ax
        mov     [tx_descs + EL3_DESC_ADDR + 2], dx
        xor     ax, ax
        mov     [tx_descs + EL3_DESC_NEXT], ax
        mov     [tx_descs + EL3_DESC_NEXT + 2], ax
        mov     [tx_descs + EL3_DESC_STATUS], ax
        mov     [tx_descs + EL3_DESC_STATUS + 2], ax
        mov     word [tx_descs + EL3_DESC_LEN], COH_FRAME_LEN
        mov     [tx_descs + EL3_DESC_LEN + 2], ax
        db      0x0F, 0x09                              ; WBINVD
        mov     ax, [es:NCA_DST + COH_PAT_OFF]          ; read-allocate iff still cacheable
        mov     ax, [es:NCA_SRC + COH_PAT_OFF]
        mov     ax, [es:NCA_UPD + EL3_DESC_STATUS]
        mov     word [es:NCA_SRC + COH_PAT_OFF],     WB_PAT_NEW  ; CPU write the card must see
        mov     word [es:NCA_SRC + COH_PAT_OFF + 2], WB_PAT_NEW
        ; kick: ack stale completions, UpListPtr <- area, StartDmaUp; DownListPtr <- tx_descs, StartDmaDown
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_ACK_INTR | EL3_ST_UP_COMPLETE | 0x0200
        out     dx, ax
        mov     ax, [nc_area_phys]
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_UP_LIST_PTR
        out     dx, ax
        mov     ax, [nc_area_phys + 2]
        add     dx, 2
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_START_DMA_UP
        out     dx, ax
        push    si
        mov     si, tx_descs
        call    cs_phys
        pop     si
        push    dx
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_DOWN_LIST_PTR
        out     dx, ax
        pop     ax
        add     dx, 2
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_START_DMA_DOWN
        out     dx, ax
        call    coh_wait_up                             ; clobbers ES
        jc      .cnt_fail
        mov     es, [nc_area_seg]
        cmp     word [es:NCA_DST + COH_PAT_OFF], WB_PAT_NEW
        jne     .cnt_fail
        cmp     word [es:NCA_DST + COH_PAT_OFF + 2], WB_PAT_NEW
        jne     .cnt_fail
        test    word [es:NCA_UPD + EL3_DESC_STATUS], EL3_DESC_UP_COMPLETE
        jz      .cnt_fail
        clc
        ret
.cnt_fail:
        stc
        ret

;------------------------------------------------------------------------------
; coh_one_trial -- one MAC-loopback RX-coherency trial (loopback must already be enabled). DI = dest buffer
; (>= COH_BUF_LEN). Seeds dest = A, builds the descriptors, writes back (WBINVD where safe) so the card
; fetches fresh descriptors + source, then READS dest (allocating its line even on a cache that does not
; allocate on a write miss -- else the warm is a no-op and a non-coherent cache reads fresh by accident),
; loopback-TXes B into it, waits for UpComplete in IntStatus (I/O), and reads dest with NO flush.
; CF=0 -> read fresh B (coherent); CF=1 -> stale A or timeout. Clobbers AX,BX,CX,DX,SI,ES; DI preserved.
;------------------------------------------------------------------------------
coh_one_trial:
        mov     word [di + COH_PAT_OFF],     COH_PAT_A  ; seed the dest with A (the stale marker)
        mov     word [di + COH_PAT_OFF + 2], COH_PAT_A
        mov     word [coh_tx_buf + COH_PAT_OFF],     COH_PAT_B  ; (re)stamp the loopback source with B
        mov     word [coh_tx_buf + COH_PAT_OFF + 2], COH_PAT_B
        mov     si, coh_tx_buf                          ; SI=src, DI=dest -> build descriptors
        call    coh_build_descs
        cmp     byte [g_wbinvd_ok], 0
        je      .cot_nofl
        db      0x0F, 0x09                              ; WBINVD: descriptors + source + dest(A) -> memory
.cot_nofl:
        mov     ax, [di + COH_PAT_OFF]                  ; read-allocate the dest line (holds A if cached)
        call    coh_start_dma
        call    coh_wait_up
        jc      .cot_stale                              ; timeout -> treat as stale (can't prove fresh)
        cmp     word [di + COH_PAT_OFF], COH_PAT_B      ; read the dest with NO flush
        jne     .cot_stale
        cmp     word [di + COH_PAT_OFF + 2], COH_PAT_B
        jne     .cot_stale
        clc                                             ; fresh -> coherent
        ret
.cot_stale:
        stc
        ret

;------------------------------------------------------------------------------
; coh_wait_up -- wait for the loopback frame's upload: poll IntStatus (an I/O port, never cached) for
; UpComplete, bounded by EL3_DMA_TX_TICKS BIOS ticks, then ack it. CF=0 done; CF=1 timeout.
; Clobbers AX,BX,DX,ES. Cold.
;------------------------------------------------------------------------------
coh_wait_up:
        xor     ax, ax
        mov     es, ax
        mov     bx, [es:BIOS_TICK_COUNT]
.cwu_poll:
        mov     dx, [g_nic_io]
        add     dx, EL3_STATUS
        in      ax, dx
        test    ax, EL3_ST_UP_COMPLETE
        jnz     .cwu_done
        mov     ax, [es:BIOS_TICK_COUNT]
        sub     ax, bx
        cmp     ax, EL3_DMA_TX_TICKS
        jb      .cwu_poll
        stc
        ret
.cwu_done:
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_ACK_INTR | EL3_ST_UP_COMPLETE | 0x0200  ; + DnComplete (bit 9)
        out     dx, ax
        clc
        ret

;------------------------------------------------------------------------------
; coh_build_descs -- build the internal-loopback descriptor pair: RX up-descriptor dest=DI (LEN=COH_BUF_LEN
; capacity), TX down-descriptor src=SI (LEN=COH_FRAME_LEN, reuses tx_descs); NEXT/STATUS=0. Does NOT touch
; the buffer contents. Preserves DI,SI; clobbers AX,BX,CX,DX. Split from coh_start_dma so the WB probe can
; WBINVD BETWEEN building the descriptors and starting the DMA (so the flush also lands the descriptors in
; memory -> the card reads them coherently on the very write-back cache being probed). Cold.
;------------------------------------------------------------------------------
coh_build_descs:
        push    di
        push    si
        mov     si, di                                  ; up-descriptor: ADDR=phys(DI)
        call    cs_phys
        mov     [coh_up_desc + EL3_DESC_ADDR], ax
        mov     [coh_up_desc + EL3_DESC_ADDR + 2], dx
        xor     ax, ax
        mov     [coh_up_desc + EL3_DESC_NEXT], ax
        mov     [coh_up_desc + EL3_DESC_NEXT + 2], ax
        mov     [coh_up_desc + EL3_DESC_STATUS], ax
        mov     [coh_up_desc + EL3_DESC_STATUS + 2], ax
        mov     word [coh_up_desc + EL3_DESC_LEN], COH_BUF_LEN
        mov     [coh_up_desc + EL3_DESC_LEN + 2], ax
        pop     si                                      ; down-descriptor (tx_descs): ADDR=phys(SI=src)
        push    si
        call    cs_phys
        mov     [tx_descs + EL3_DESC_ADDR], ax
        mov     [tx_descs + EL3_DESC_ADDR + 2], dx
        xor     ax, ax
        mov     [tx_descs + EL3_DESC_NEXT], ax
        mov     [tx_descs + EL3_DESC_NEXT + 2], ax
        mov     [tx_descs + EL3_DESC_STATUS], ax
        mov     [tx_descs + EL3_DESC_STATUS + 2], ax
        mov     word [tx_descs + EL3_DESC_LEN], COH_FRAME_LEN
        mov     [tx_descs + EL3_DESC_LEN + 2], ax
        pop     si
        pop     di
        ret

;------------------------------------------------------------------------------
; coh_start_dma -- kick the loopback: UpListPtr <- phys(coh_up_desc) + StartDmaUp, then DownListPtr <-
; phys(tx_descs) + StartDmaDown. Reads only the descriptor ADDRESSES (cs_phys, not memory) so it leaves the
; just-flushed descriptor bytes untouched. Clobbers AX,CX,DX,SI. Cold.
;------------------------------------------------------------------------------
coh_start_dma:
        mov     dx, [g_nic_io]                          ; clear any stale Up/DnComplete so coh_wait_up
        add     dx, EL3_CMD                             ; only sees THIS transfer's completion
        mov     ax, EL3_CMD_ACK_INTR | EL3_ST_UP_COMPLETE | 0x0200
        out     dx, ax
        mov     si, coh_up_desc                         ; arm RX
        call    cs_phys
        push    dx
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_UP_LIST_PTR
        out     dx, ax
        pop     ax
        add     dx, 2
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_START_DMA_UP
        out     dx, ax
        mov     si, tx_descs                            ; kick TX (loopback)
        call    cs_phys
        push    dx
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_DOWN_LIST_PTR
        out     dx, ax
        pop     ax
        add     dx, 2
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_START_DMA_DOWN
        out     dx, ax
        ret

;------------------------------------------------------------------------------
; coh_is_writeback -- WRITE-BACK vs write-through discriminator (486+; WBINVD available). Chipset NC fences
; only help write-back caches: on a write-through cache the CPU's writes reach memory immediately so the bus
; master reads them fresh, and chipset NC is the wrong tool (invalidation already suffices). Probe the
; CPU-WRITE->card-READ direction (the base test only probes card-WRITE->CPU-READ, which is stale on BOTH WT
; and WB):
;   - build the descriptors, write OLD into the (cached) src, then WBINVD -> memory holds the descriptors
;     AND src=OLD, cache clean
;   - READ src (allocates the line clean), then write NEW with NO flush -> a write HIT: WB: cache=NEW dirty,
;     memory[src] STILL OLD; WT: memory[src]=NEW (holds for caches that don't allocate on a write miss too)
;   - loopback src -> a VIRGIN dest (the card DMA-reads memory[src]); read the dest (virgin first-touch is a
;     fresh memory read): dest == OLD -> the card saw stale memory -> WRITE-BACK (CF=1, NC-eligible)
;                         dest == NEW -> the card saw fresh memory -> write-through / no cache (CF=0)
; coh_wb_dst is 32-aligned + untouched after the WBINVD so its first cache line can't be pre-loaded (which
; would fake a fresh read). Completion is polled in IntStatus (I/O), never in the cached descriptor; the
; verdict is the virgin dest. On the cacheless emulator memory always = NEW -> CF=0 (correctly not-WB; the
; CFG_FORCE_NC call site overrides to keep the NC structural test alive). Clobbers AX,BX,CX,DX,SI,DI,ES. Cold.
;------------------------------------------------------------------------------
WB_PAT_OLD      equ 0x0F0F                              ; pre-flush memory value (seen iff writes sit dirty in cache)
WB_PAT_NEW      equ 0xF0F0                              ; post-flush value written WITHOUT a flush
coh_is_writeback:
        mov     di, coh_wb_dst                          ; dest = virgin; src = coh_wb_src
        mov     si, coh_wb_src
        call    coh_build_descs                         ; build BEFORE the WBINVD so the flush lands them too
        mov     word [coh_wb_src + COH_PAT_OFF],     WB_PAT_OLD  ; src = OLD
        mov     word [coh_wb_src + COH_PAT_OFF + 2], WB_PAT_OLD
        db      0x0F, 0x09                              ; WBINVD: descriptors + src(OLD) -> memory; invalidate
        ; READ src first so its line is allocated (clean). Then the NEW store is a write HIT, which a write-back
        ; cache holds dirty (memory stays OLD) and a write-through cache sends on to memory. Storing NEW straight
        ; after the WBINVD would be a write MISS instead, and caches that don't allocate on a write miss (P5 L1,
        ; Intel 486 WB L1, most 486 L2s) send a miss to memory -> a false "write-through" verdict.
        mov     ax, [coh_wb_src + COH_PAT_OFF]
        mov     word [coh_wb_src + COH_PAT_OFF],     WB_PAT_NEW  ; src = NEW, NO flush
        mov     word [coh_wb_src + COH_PAT_OFF + 2], WB_PAT_NEW
        call    coh_start_dma                           ; card DMA-reads memory[src] -> virgin dest
        call    coh_wait_up                             ; completion via IntStatus (I/O, never cached)
        jc      .wb_through                             ; no completion -> can't prove write-back
        cmp     word [coh_wb_dst + COH_PAT_OFF], WB_PAT_OLD  ; dest uncached since the WBINVD -> a fresh
        jne     .wb_through                                  ; memory read: OLD -> the card saw stale memory
        stc                                             ; write-back -> NC-eligible
        ret
.wb_through:
        clc                                             ; write-through / no cache -> NC not the tool
        ret

; cs_phys -- 20-bit physical address of CS:si -> dx:ax (dx = top 4 bits). Clobbers CX only. Cold helper.
cs_phys:
        mov     ax, cs
        mov     cl, 4
        shl     ax, cl
        mov     dx, cs
        mov     cl, 12
        shr     dx, cl
        add     ax, si
        adc     dx, 0
        ret

; coherency-probe cold scratch (reclaimed after install): a loopback TX source carrying pattern B (its
; down-list reuses tx_descs), a dedicated RX up-descriptor, and the RX dest the card DMA-writes into.
coh_tx_buf:      db 0xFF,0xFF,0xFF,0xFF,0xFF,0xFF   ; broadcast DA (passes the RX address filter)
                 times COH_FRAME_LEN - 6 db 0
coh_trials_left: db 0
coh_up_desc:     times EL3_DESC_SIZE db 0
coh_rx_buf:      times COH_BUF_LEN db 0
; WB-discriminator buffers (coh_is_writeback): the card reads coh_wb_src (CPU-written) and RX-DMAs into the
; VIRGIN coh_wb_dst. 32-byte aligned so coh_wb_dst's first cache line is never shared with coh_wb_src -- else
; writing coh_wb_src=NEW would pre-cache coh_wb_dst's line and fake a "fresh" read on a write-back cache.
        alignb 32
coh_wb_src:      db 0xFF,0xFF,0xFF,0xFF,0xFF,0xFF   ; broadcast DA
                 times COH_FRAME_LEN - 6 db 0
        alignb 32
coh_wb_dst:      times COH_BUF_LEN db 0
coh_probe_end:                                  ; end of the cold bus-master probe span (V86 VDS proof)

; detect_nic / id_read_eeprom / io_delay -- the real 3C509B ISA probe + activation.
%include "el3_probe.asm"

; el3_init -- operational bring-up of the activated card (MAC, media, RX/TX enable).
%include "el3_init.asm"

; copybreak_autotune -- compute the RX copybreak threshold T (cost model + PIT-timed PIO probe).
%include "copybreak.asm"

%ifdef CFG_PNP
; detect_nic_pnp -- direct ISA PnP isolation (3C515 / PnP-mode 3C509B). >=286-gated by caller.
%include "isapnp.asm"
%endif

; install -- hook INT 60h + NIC IRQ, enable card int, free environment, DOS TSR-keep.
%include "install.asm"

;------------------------------------------------------------------------------
; build_plan -- resolve the per-generation hardware parameters and hand the composer its
; immediates. Two generation-dependent values: the Window-1 register base (3C509 at io_base,
; Corkscrew at io_base+0x10) and the SET_TX_START command (3C509 early-start vs 3C515
; store-and-forward). The PIO datapath FIFO immediate is the Window-1 base.
;------------------------------------------------------------------------------
build_plan:
        mov     ax, EL3_W1_DELTA_3C509                       ; default: 3C509/B layout
        cmp     byte [g_nic_gen], 0
        je      .gen_done
        mov     ax, EL3_W1_DELTA_VORTEX                      ; 3C515: registers relocated +0x10
.gen_done:
        add     ax, [g_nic_io]
        mov     [g_w1_base], ax             ; Window-1 data-register base (FIFO/status/free)
        ; PIO TX uses early-start on BOTH generations: the wire overlaps the FIFO fill, keeping a
        ; CPU that fills faster than the wire near wire rate at 10 Mbit. (The ~16x store-and-forward
        ; penalty once measured here -- 598 vs 9717 kbit/s at 286/10M -- was an emulator artifact: it
        ; didn't start a complete frame that sat below the threshold. Fixed in elink-qemu; SF costs
        ; only the lost overlap.) DMA TX bypasses this FIFO threshold entirely.
        ; EXCEPT the 8088 class: its fill (~0.3 MB/s at 4.77 MHz) is slower than the 10 Mbit wire drain
        ; (1.25 MB/s), so early start underruns any frame much over the threshold -- the frame is lost and
        ; every retransmit underruns again. Store-and-forward there (tx_status_drain also raises the
        ; threshold adaptively after an underrun on any CPU).
        mov     bx, EL3_CMD_SET_TX_START | EL3_TX_START_THRESH
        cmp     byte [g_cpu_class], CPU_8088
        jne     .tx_start_set
        mov     bx, EL3_CMD_SET_TX_START | EL3_TX_THRESH_SF
.tx_start_set:
        mov     [g_tx_start], bx            ; precomputed SET_TX_START command
        mov     [g_plan_rx_imm], ax         ; PIO datapath FIFO immediate = Window-1 base
        mov     [g_plan_tx_imm], ax
        ; --- resolve bus-master single-transfer TX DMA: /d AND 3C515 AND >=286 (else PIO floor) ---
        mov     byte [g_use_dma], 0
        cmp     byte [g_want_dma], 0
        je      .dma_resolved
        cmp     byte [g_nic_gen], 1             ; Corkscrew (3C515) only -- has the bus-master engine
        jne     .dma_resolved
        cmp     byte [g_cpu_class], CPU_80286   ; >=286: real mode, phys = seg*16+off, 24-bit ISA-safe
        jb      .dma_resolved
        mov     byte [g_use_dma], 1
.dma_resolved:
        ; Zero-copy async TX ring (AH=0xF1) is available on ANY bus-master config (>=286): dma_tx_async
        ; is 8086-clean and does no per-frame copy, so the 286 limitation (no movsd) doesn't apply.
        mov     al, [g_use_dma]
        mov     [g_async], al
        ; send_pkt's resident DMA path: 386+ uses the non-blocking COPY ring (movsd slot copy); a 286
        ; can't hide that per-frame copy (no movsd), so its send_pkt uses the blocking zero-copy
        ; single-transfer instead -- ~+47% at 100 Mbit (28668 vs 19570 kbit/s). (Async is separate.)
        mov     byte [g_tx_ring], 0
        cmp     byte [g_cpu_class], CPU_80386
        jb      .ring_resolved
        mov     byte [g_tx_ring], 1
.ring_resolved:
        ; --- resolve FDDI-sized large frames: /j AND 3C515 (else standard Ethernet). Sets the RX
        ;     length mask to the 13-bit Corkscrew field so a >2047 B frame's length isn't truncated.
        ;     el3_init sets allowLargePackets in MacControl when g_use_large. ---
        mov     byte [g_use_large], 0
        mov     word [g_tx_slot_sz], TX_SLOT_SZ  ; standard TX ring slots unless /j
        mov     word [g_rx_len_mask], 0x07FF     ; default: standard Ethernet (11-bit-safe)
        cmp     byte [g_want_large], 0
        je      .large_resolved
        cmp     byte [g_nic_gen], 1              ; Corkscrew (3C515) only
        jne     .large_resolved
        mov     byte [g_use_large], 1
        mov     word [g_tx_slot_sz], TX_SLOT_LARGE   ; FDDI-sized TX ring slots
        mov     word [g_rx_len_mask], 0x1FFF     ; 13-bit length field (FDDI-sized RX)
.large_resolved:
        call    dma_v86_forbid_check    ; V86 + no VDS -> force the PIO floor (dma.h DMA_POLICY_FORBID)
        ret

;------------------------------------------------------------------------------
; dma_v86_forbid_check -- under a paging memory manager (V86) WITHOUT VDS we cannot get a safe bus-master
; physical (seg<<4 is a lie when low memory is remapped, and there's no VDS to translate/lock), so fall
; back to the PIO floor -- dma.h's DMA_POLICY_FORBID. Real mode keeps DMA (seg<<4 valid). V86 *with* VDS
; keeps DMA only once it is PROVEN: the 386+ ring, and a VDS lock of the driver's DMA span (and the cold
; probe span) that reports phys == seg<<4. AH=F1 stack buffers are VDS-locked per send (tx_v86_phys);
; the RX conv ring gets the true physical from the VDS-locking stack (XMS_POLICY_COMMONBUF). Also records
; g_v86 and g_wbinvd_ok. Cold; clobbers AX, CX, DX, ES. Only reached on >=286 (SMSW).
;------------------------------------------------------------------------------
dma_v86_forbid_check:
        mov     byte [g_v86], 0
        mov     byte [g_vds_span_held], 0       ; VDS lock bookkeeping (resb: not load-zeroed)
        mov     byte [g_vds_cold_held], 0
        push    di
        mov     di, tx_vds_held
        mov     cx, TX_RING_N
        xor     al, al
        push    es
        push    ds
        pop     es
        rep     stosb
        pop     es
        pop     di
        cmp     byte [g_use_dma], 0
        je      .dvf_done               ; already PIO -> nothing to forbid
        push    es
        db      0x0F, 0x01, 0xE0        ; SMSW AX (bytes: legal in V86, 286+; the DMA path is >=286)
        and     al, 1                   ; CR0.PE: 1 = a protected-mode host is paging us (V86); 0 = real mode
        mov     [g_v86], al
        ; WBINVD (the only flush tier) is usable on a 486+ in real mode, or under V86 only when /v says the
        ; host emulates it. Decided here (before any probe) so no cold phase ever issues it unguarded.
        mov     byte [g_wbinvd_ok], 0
        cmp     byte [g_cpu_class], CPU_80486
        jb      .dvf_wb_set
        cmp     al, 0
        je      .dvf_wb_yes
        cmp     byte [g_want_v86trust], 0
        je      .dvf_wb_set
.dvf_wb_yes:
        mov     byte [g_wbinvd_ok], 1
.dvf_wb_set:
        cmp     byte [g_v86], 0
        je      .dvf_keep               ; real mode -> seg<<4 is the bus address -> keep DMA
        xor     ax, ax
        mov     es, ax
        test    byte [es:0x047B], 0x20  ; BIOS data 0040:007Bh bit 5 = VDS available
        jz      .dvf_forbid             ; V86 + no VDS -> can't address safely -> PIO floor
        ; V86 + VDS: seg<<4 must be PROVEN, not assumed. Require the 386+ ring (a /2-forced 286 send_pkt
        ; zero-copies the caller's buffer at seg<<4, dma_tx_single), then VDS-lock the driver's whole DMA
        ; span [tx_descs, resident_end) -- descriptors, TX slots, RX descriptors -- and require phys ==
        ; seg<<4 (identity). Hold that lock for the driver's lifetime. Also prove the cold probe span the
        ; bus-master probes DMA into (released after them). AH=F1 stack buffers are VDS-locked per send.
        cmp     byte [g_tx_ring], 0
        je      .dvf_forbid
        push    bx
        push    si
        push    di
        mov     bx, cs
        mov     di, tx_span_dds
        mov     si, tx_descs
        mov     ax, [g_tx_slot_sz]              ; span = [tx_descs, end of the kept TX slots)
        mov     cx, TX_RING_N
        mul     cx
        add     ax, tx_slots - tx_descs
        mov     cx, ax
        call    vds_lock_prove
        jc      .dvf_pop_forbid
        mov     byte [g_vds_span_held], 1
        mov     di, cold_dds
        mov     si, bm_test_buf
        mov     cx, coh_probe_end - bm_test_buf
        call    vds_lock_prove
        jc      .dvf_unspan
        mov     byte [g_vds_cold_held], 1
        pop     di
        pop     si
        pop     bx
        jmp     .dvf_keep
.dvf_unspan:
        mov     di, tx_span_dds
        call    vds_unlock_di
        mov     byte [g_vds_span_held], 0
.dvf_pop_forbid:
        pop     di
        pop     si
        pop     bx
.dvf_forbid:
        call    dma_force_pio
.dvf_keep:
        pop     es
.dvf_done:
        ret

;------------------------------------------------------------------------------
; vds_lock_prove -- VDS-lock BX:SI, CX bytes via the DDS at CS:DI and require an in-place lock whose
; physical address equals (BX<<4)+SI (identity-mapped under the V86 host). CF=0 -> locked (caller owns the
; lock); CF=1 -> not provable (nothing left locked). DX=0 (JEMM386 rejects the no-alloc flag); a bounce
; buffer shows as buffer_id != 0. Cold; clobbers AX, CX, DX.
;------------------------------------------------------------------------------
vds_lock_prove:
        mov     [di + DDS_SIZE], cx
        mov     [di + DDS_OFFSET], si
        mov     [di + DDS_SEGMENT], bx
        xor     ax, ax
        mov     [di + DDS_SIZE + 2], ax
        mov     [di + DDS_OFFSET + 2], ax
        mov     [di + DDS_BUFID], ax
        mov     [di + DDS_PHYS], ax
        mov     [di + DDS_PHYS + 2], ax
        push    es
        push    cs
        pop     es                              ; ES:DI = DDS
        mov     ax, VDS_LOCK_REGION
        xor     dx, dx
        stc                                     ; an unhooked INT 4Bh must read as failure
        int     0x4B
        pop     es
        jc      .vlp_fail                       ; CF alone signals failure
        cmp     word [di + DDS_BUFID], 0
        jne     .vlp_unlock                     ; bounce buffer -> not in place
        mov     ax, bx
        mov     dx, bx
        mov     cl, 4
        shl     ax, cl
        mov     cl, 12
        shr     dx, cl
        add     ax, si
        adc     dx, 0                           ; dx:ax = (BX<<4) + SI
        cmp     ax, [di + DDS_PHYS]
        jne     .vlp_unlock
        cmp     dx, [di + DDS_PHYS + 2]
        jne     .vlp_unlock
        clc
        ret
.vlp_unlock:
        push    es
        call    vds_unlock_di
        pop     es
.vlp_fail:
        stc
        ret

;------------------------------------------------------------------------------
; vds_cold_release -- after the bus-master probes: release the cold probe span's VDS lock, and if the
; probes dropped DMA (PIO fallback) release the resident span lock too (the DMA region is freed).
; Cold; clobbers AX, DX, DI.
;------------------------------------------------------------------------------
vds_cold_release:
        push    es
        cmp     byte [g_vds_cold_held], 0
        je      .vcr_span
        mov     di, cold_dds
        call    vds_unlock_di
        mov     byte [g_vds_cold_held], 0
.vcr_span:
        cmp     byte [g_use_dma], 0
        jne     .vcr_done
        cmp     byte [g_vds_span_held], 0
        je      .vcr_done
        mov     di, tx_span_dds
        call    vds_unlock_di
        mov     byte [g_vds_span_held], 0
.vcr_done:
        pop     es
        ret

;------------------------------------------------------------------------------
; dma_force_pio -- drop to the PIO floor: clear EVERY bus-master flag together. install keeps only up to
; resident_end_pio when g_use_dma == 0, so a flag left set (g_async -> AH=F1 dma_tx_async, g_tx_ring)
; would let a resident path touch the freed DMA region (tx_descs / xms_* state). Cold; no clobbers.
;------------------------------------------------------------------------------
dma_force_pio:
        mov     byte [g_use_dma], 0
        mov     byte [g_async], 0
        mov     byte [g_tx_ring], 0
        ; fall through: a probe that timed out may still have a descriptor armed -> stop both engines

;------------------------------------------------------------------------------
; dma_quiesce -- stop the 3C515 up/down DMA engines and zero both list pointers, so a transfer the cold
; probes left pending (phase_validate_dma, the coherency loopback -- a timeout there leaves the descriptor
; armed) can never land later in cold memory that install reclaims, or in the DMA region the PIO floor
; frees. Stall -> clear ptr -> unstall per engine (a null list pointer leaves the engine idle), then ack
; any Up/DnComplete it latched. Only reached with a 3C515 (g_use_dma was set). Cold; clobbers AX, DX.
;------------------------------------------------------------------------------
dma_quiesce:
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_UP_STALL
        out     dx, ax
        mov     ax, EL3_CMD_DOWN_STALL
        out     dx, ax
        xor     ax, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_UP_LIST_PTR
        out     dx, ax
        add     dx, 2
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CS_DOWN_LIST_PTR
        out     dx, ax
        add     dx, 2
        out     dx, ax
        mov     dx, [g_nic_io]
        add     dx, EL3_CMD
        mov     ax, EL3_CMD_UP_UNSTALL
        out     dx, ax
        mov     ax, EL3_CMD_DOWN_UNSTALL
        out     dx, ax
        mov     ax, EL3_CMD_ACK_INTR | EL3_ST_UP_COMPLETE | 0x0200   ; + DnComplete (bit 9)
        out     dx, ax
        ret

;------------------------------------------------------------------------------
; compose_resident -- select + stitch + patch the planned fragments into resident_image.
; Records each fragment's landing offset in g_off[]. 8088-clean (movsb/stosw/loops).
; out: AX = emitted length (0 on missing fragment / over budget).
;------------------------------------------------------------------------------
compose_resident:
        ; g_off[] = 0xFFFF
        mov     di, g_off
        mov     cx, FRAG__COUNT
        mov     ax, 0xFFFF
        rep     stosw                   ; ES:DI (= DGROUP)

        mov     word [g_pos], 0
        mov     word [g_planptr], g_plan
        mov     word [g_step], G_PLAN_N
.step:
        mov     si, [g_planptr]
        mov     al, [si]                ; frag id
        mov     [g_curid], al
        inc     si
        mov     ax, [si]                ; imm0
        mov     [g_imm0], ax
        add     si, 2
        mov     [g_planptr], si

        mov     al, [g_curid]
        call    frag_lookup             ; -> DI = entry, CF=1 if none
        jc      .fail

        ; g_off[id] = pos
        mov     bl, [g_curid]
        xor     bh, bh
        shl     bx, 1
        mov     ax, [g_pos]
        mov     [g_off + bx], ax

        ; copy fragment bytes: resident_image[pos..] = entry.bytes[0..len)
        mov     cx, [di + 4]            ; len
        mov     si, [di + 6]            ; src ptr
        push    di
        mov     di, resident_image
        add     di, [g_pos]
        rep     movsb                   ; DS:SI -> ES:DI
        pop     di

        ; apply immediate patches (floor: all PATCH_IMM16 = io_base)
        xor     ch, ch
        mov     cl, [di + 2]            ; n_patches
        jcxz    .nopatch
        mov     si, [di + 8]            ; patch table ptr
.patch:
        mov     bx, [si]                ; patch.offset (within fragment)
        add     bx, [g_pos]
        mov     ax, [g_imm0]
        mov     [resident_image + bx], ax
        add     si, PATCH_ENTRY_SIZE
        loop    .patch
.nopatch:
        mov     ax, [di + 4]            ; pos += len
        add     [g_pos], ax

        dec     word [g_step]
        jnz     .step

        mov     ax, [g_pos]
        ret
.fail:
        xor     ax, ax
        ret

;------------------------------------------------------------------------------
; frag_lookup -- find the best fragment for (id=AL, class=g_cpu_class): matching id with
; the highest cpu_min that is <= the detected class. out: DI = entry, CF=0; CF=1 if none.
; clobbers BX, CX, DX (and DI).
;------------------------------------------------------------------------------
frag_lookup:
        mov     di, g_frags
        mov     cx, FRAG_TABLE_N
        xor     bx, bx                  ; bx = best entry (0 = none yet)
        xor     dl, dl                  ; dl = best cpu_min
.fl_loop:
        cmp     [di], al                ; entry.id == id?
        jne     .fl_next
        mov     dh, [di + 1]            ; entry.cpu_min
        cmp     dh, [g_cpu_class]
        ja      .fl_next                ; cpu_min > class -> not emittable
        or      bx, bx
        jz      .fl_take                ; first match
        cmp     dh, dl
        jbe     .fl_next                ; not a higher cpu_min than current best
.fl_take:
        mov     bx, di
        mov     dl, dh
.fl_next:
        add     di, FRAG_ENTRY_SIZE
        loop    .fl_loop

        or      bx, bx
        jz      .fl_none
        mov     di, bx
        clc
        ret
.fl_none:
        stc
        ret

;------------------------------------------------------------------------------
; copy_down -- floor: the image was composed in place in resident_image (no relocs in the
; PIO floor fragments), so this just reports the size in paragraphs. Real packing + reloc
; fixups arrive with cross-fragment references. in: AX = emitted len; out: AX = paragraphs.
;------------------------------------------------------------------------------
copy_down:
        add     ax, 15
        mov     cl, 4
        shr     ax, cl                  ; ceil(len / 16)
        ret

;------------------------------------------------------------------------------
; Diagnostic print helpers (COLD; DOS INT 21h). Clobber AX/CX/DX freely.
;------------------------------------------------------------------------------
print_str:                              ; DS:DX -> '$'-terminated string
        mov     ah, 9
        int     0x21
        ret
print_char:                             ; AL = character
        mov     dl, al
        mov     ah, 2
        int     0x21
        ret
print_hex16:                            ; AX = value -> 4 hex digits
        push    ax
        mov     al, ah
        call    print_hex8
        pop     ax
        call    print_hex8
        ret
print_hex8:                             ; AL = byte -> 2 hex digits
        push    ax
        mov     cl, 4
        shr     al, cl                  ; high nibble
        call    print_nib
        pop     ax                      ; low nibble (print_nib masks)
        call    print_nib
        ret
print_nib:                              ; AL low nibble -> hex char
        and     al, 0x0F
        add     al, '0'
        cmp     al, '9'
        jbe     .e
        add     al, 7                   ; 'A'..'F'
.e:
        mov     dl, al
        mov     ah, 2
        int     0x21
        ret
print_mac:                              ; " MAC=" + g_mac[0..5] as hex
        mov     dx, msg_mac
        call    print_str
        mov     si, g_mac
        mov     cx, 6
.pm:
        push    cx
        lodsb
        call    print_hex8
        pop     cx
        loop    .pm
        ret

;------------------------------------------------------------------------------
; validate_mac -- sanity-check the station address in g_mac[0..5] before the driver
; builds the resident image on it. A read from an unmapped/off-device window returns
; 0xFF on every byte (the failure mode behind a wrong /5 gen on a 3C509: el3_load_mac_io
; lands the MAC read at the +0x2000 alias, off the card), and an EEPROM that never
; loaded reads back all-00. A real station address is also always unicast (bit 0 of the
; first byte clear). Reject all three. 8088-clean. out: CF=1 invalid, CF=0 plausible.
; Clobbers AX, CX, SI (DL preserved via push).
;------------------------------------------------------------------------------
validate_mac:
        test    byte [g_mac], 1         ; I/G bit set -> multicast/broadcast, not a station addr
        jnz     .bad
        push    dx
        mov     si, g_mac
        mov     cx, 6
        mov     ah, 0xFF                ; AND-accumulator: stays 0xFF iff every byte is 0xFF
        xor     dl, dl                  ; OR-accumulator:  stays 0x00 iff every byte is 0x00
.vm:
        lodsb
        and     ah, al
        or      dl, al
        loop    .vm
        cmp     ah, 0xFF                ; all bytes 0xFF -> off-device / unmapped read
        je      .bad_pop
        or      dl, dl                  ; all bytes 0x00 -> EEPROM never loaded
        jz      .bad_pop
        pop     dx
        clc
        ret
.bad_pop:
        pop     dx
.bad:
        stc
        ret

;------------------------------------------------------------------------------
; parse_hex16 / parse_dec16 -- read a number from the command tail (ES:SI), stopping at the
; first non-digit. out: BX = value, SI advanced past the digits. Clobbers AX, CX (and DX/dec).
;------------------------------------------------------------------------------
parse_hex16:
        xor     bx, bx
.ph:    mov     al, [es:si]
        cmp     al, '0'
        jb      .ph_done
        cmp     al, '9'
        jbe     .ph_d09
        or      al, 0x20                ; tolower
        cmp     al, 'a'
        jb      .ph_done
        cmp     al, 'f'
        ja      .ph_done
        sub     al, 'a' - 10            ; 'a'..'f' -> 10..15
        jmp     .ph_acc
.ph_d09:
        sub     al, '0'                 ; '0'..'9' -> 0..9
.ph_acc:
        mov     cl, 4
        shl     bx, cl                  ; bx *= 16
        xor     ah, ah
        add     bx, ax
        inc     si
        jmp     .ph
.ph_done:
        ret

parse_dec16:
        xor     bx, bx
.pd:    mov     al, [es:si]
        cmp     al, '0'
        jb      .pd_done
        cmp     al, '9'
        ja      .pd_done
        sub     al, '0'
        mov     cx, bx                  ; bx = bx*10 + digit  (10x = ((4x)+x)*2)
        shl     bx, 1
        shl     bx, 1
        add     bx, cx
        shl     bx, 1
        xor     ah, ah
        add     bx, ax
        inc     si
        jmp     .pd
.pd_done:
        ret
