#!/usr/bin/env python3
"""mkfrag.py -- assemble PIC hot-path fragments and emit a NASM fragment table.

Each fragment in src/asm/frag/ is assembled with `nasm -f bin` (flat, position-
independent, org 0). The resulting bytes and patch-slot offsets are written to
build/frags_asm.inc, which src/asm/start.asm %includes (inside segment _DATA) to
populate g_frags[].

Patch slots are located by scanning the assembled bytes for a unique 16-bit sentinel
(see SENTINELS). Exactly one occurrence is required per slot -- the build fails loudly
otherwise, so editing a fragment can never silently move a patch offset.

Entry layout (must match include/codegen.inc):
  db id, cpu_min, n_patches, 0 ; dw len, bytes_ptr, patches_ptr   (10 bytes)
Patch entry: dw offset ; db kind                                   (3 bytes)

See docs/02-resident-construction.md.
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FRAG_DIR = os.path.join(ROOT, "src", "asm", "frag")
INC_DIR = os.path.join(ROOT, "include")
BUILD_DIR = os.path.join(ROOT, "build")
OUT = os.path.join(BUILD_DIR, "frags_asm.inc")
NASM = os.environ.get("NASM", "nasm")

# Patch slot index -> (16-bit sentinel baked into the fragment, kind equate name).
SENTINELS = [
    (0xE3A7, "PATCH_IMM16"),   # slot 0: io_base
]

# (source file, frag_id equate, cpu_min equate, number of patch slots used)
# Multiple fragments may share a frag_id with different cpu_min; frag_lookup selects the
# highest cpu_min <= the detected CPU class (e.g. the 8088 unrolled loop vs the 286 rep
# insw/outsw burst, which needs a 16-bit ISA bus).
FRAGS = [
    ("api.asm",       "FRAG_API_DISPATCH", "CPU_8088",  0),
    ("isr_entry.asm", "FRAG_ISR_ENTRY",    "CPU_8088",  0),
    ("isr_eoi.asm",   "FRAG_ISR_EOI",      "CPU_8088",  0),
    ("rx_pio.asm",    "FRAG_RX_PIO",       "CPU_8088",  1),  # 8088: unrolled loop
    ("tx_pio.asm",    "FRAG_TX_PIO",       "CPU_8088",  1),
    ("rx_pio_286.asm", "FRAG_RX_PIO",      "CPU_80286", 1),  # 286+ (16-bit ISA): rep insw
    ("tx_pio_286.asm", "FRAG_TX_PIO",      "CPU_80286", 1),  # 286+ (16-bit ISA): rep outsw
    ("rx_pio_386.asm", "FRAG_RX_PIO",      "CPU_80386", 1),  # 386+ : 32-bit rep insd (dword FIFO)
    ("tx_pio_386.asm", "FRAG_TX_PIO",      "CPU_80386", 1),  # 386+ : 32-bit rep outsd (dword FIFO)
]


def assemble(fname):
    src = os.path.join(FRAG_DIR, fname)
    out = os.path.join(BUILD_DIR, fname[:-4] + ".bin")
    subprocess.run([NASM, "-f", "bin", "-I", INC_DIR + os.sep, src, "-o", out],
                   check=True)
    with open(out, "rb") as f:
        return f.read()


def find_sentinel(data, value, fname):
    needle = bytes([value & 0xFF, (value >> 8) & 0xFF])
    offs = [i for i in range(len(data) - 1) if data[i:i + 2] == needle]
    if len(offs) != 1:
        sys.exit("mkfrag: %s: expected exactly 1 occurrence of sentinel 0x%04X, "
                 "found %d -- pick a different sentinel" % (fname, value, len(offs)))
    return offs[0]


def nasm_db(label, data):
    body = ",".join("0x%02X" % b for b in data)
    return "%-18s db %s\n" % (label + ":", body)


def main():
    os.makedirs(BUILD_DIR, exist_ok=True)
    lines = ["; AUTO-GENERATED by tools/mkfrag.py -- do not edit.\n\n"]
    table = ["g_frags:\n"]
    for fname, fid, cpu, nslots in FRAGS:
        data = assemble(fname)
        sym = "f_" + fname[:-4]
        lines.append(nasm_db(sym, data))
        patch_sym = "0"
        if nslots:
            prows = ["%s_patches:" % sym]
            for slot in range(nslots):
                val, kind = SENTINELS[slot]
                off = find_sentinel(data, val, fname)
                prows.append("    dw %d" % off)
                prows.append("    db %s" % kind)
            lines.append("\n".join(prows) + "\n")
            patch_sym = sym + "_patches"
        table.append("    db %s, %s, %d, 0\n" % (fid, cpu, nslots))
        table.append("    dw %d, %s, %s\n" % (len(data), sym, patch_sym))
    lines.append("\n")
    lines.extend(table)
    lines.append("FRAG_TABLE_N equ %d\n" % len(FRAGS))
    with open(OUT, "w") as f:
        f.writelines(lines)
    print("mkfrag: wrote %s (%d fragments)" % (OUT, len(FRAGS)))


if __name__ == "__main__":
    main()
