#!/usr/bin/env python3
"""mkfrag.py -- assemble PIC hot-path fragments and emit a C fragment table.

Each fragment in src/asm/frag/ is assembled with `nasm -f bin` (flat, position-
independent, org 0). The resulting bytes and patch-slot offsets are written to
build/frags.inc, which src/codegen/frag_pio.c includes to populate g_frags[].

Patch slots are located by scanning the assembled bytes for a unique 16-bit sentinel
(see SENTINELS). Exactly one occurrence is required per slot -- the build fails loudly
otherwise, so editing a fragment can never silently move a patch offset.

See docs/02-resident-construction.md (fragment contract) and docs/07 (lift plan).
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FRAG_DIR = os.path.join(ROOT, "src", "asm", "frag")
INC_DIR = os.path.join(ROOT, "include")
BUILD_DIR = os.path.join(ROOT, "build")
OUT = os.path.join(BUILD_DIR, "frags.inc")
NASM = os.environ.get("NASM", "nasm")

# Patch slot index -> (16-bit sentinel baked into the fragment, frag_patch_t kind).
# Slot 0 is io_base for the PIO datapath fragments.
SENTINELS = [
    (0xE3A7, "PATCH_IMM16"),   # slot 0: io_base
]

# (source file, frag_id, cpu_min, number of patch slots used)
FRAGS = [
    ("api.asm",       "FRAG_API_DISPATCH", "CPU_8088", 0),
    ("isr_entry.asm", "FRAG_ISR_ENTRY",    "CPU_8088", 0),
    ("isr_eoi.asm",   "FRAG_ISR_EOI",      "CPU_8088", 0),
    ("rx_pio.asm",    "FRAG_RX_PIO",       "CPU_8088", 1),
    ("tx_pio.asm",    "FRAG_TX_PIO",       "CPU_8088", 1),
]


def assemble(fname):
    src = os.path.join(FRAG_DIR, fname)
    out = os.path.join(BUILD_DIR, fname[:-4] + ".bin")
    subprocess.run([NASM, "-f", "bin", "-I", INC_DIR + os.sep, src, "-o", out],
                   check=True)
    with open(out, "rb") as f:
        return f.read()


def find_sentinel(data, value, fname):
    needle = bytes([value & 0xFF, (value >> 8) & 0xFF])
    offs = [i for i in range(len(data) - 1) if data[i:i + 2] == needle]
    if len(offs) != 1:
        sys.exit("mkfrag: %s: expected exactly 1 occurrence of sentinel 0x%04X, "
                 "found %d -- pick a different sentinel" % (fname, value, len(offs)))
    return offs[0]


def c_array(name, data):
    body = ", ".join("0x%02X" % b for b in data)
    return "static const unsigned char %s[] = { %s };\n" % (name, body)


def main():
    os.makedirs(BUILD_DIR, exist_ok=True)
    lines = ["/* AUTO-GENERATED by tools/mkfrag.py -- do not edit. */\n\n"]
    entries = []
    for fname, fid, cpu, nslots in FRAGS:
        data = assemble(fname)
        sym = "f_" + fname[:-4]
        lines.append(c_array(sym, data))
        patch_sym, patch_n = "0", "0"
        if nslots:
            rows = []
            for slot in range(nslots):
                val, kind = SENTINELS[slot]
                off = find_sentinel(data, val, fname)
                rows.append("    { %d, %s }" % (off, kind))
            lines.append("static const frag_patch_t %s_patches[] = {\n%s\n};\n"
                         % (sym, ",\n".join(rows)))
            patch_sym, patch_n = sym + "_patches", str(nslots)
        entries.append("    { %s, %s, %s, %d, %s, %s, 0, 0 }"
                       % (fid, cpu, sym, len(data), patch_sym, patch_n))
    lines.append("\nstatic const fragment_t g_frags[] = {\n"
                 + ",\n".join(entries) + "\n};\n")
    with open(OUT, "w") as f:
        f.writelines(lines)
    print("mkfrag: wrote %s (%d fragments)" % (OUT, len(FRAGS)))


if __name__ == "__main__":
    main()
